vars = Variables('.SConstruct')
vars.Add(PathVariable('sherpa','path to sherpa','../..',PathVariable.PathIsDir))
env = Environment(variables=vars,CPPPATH=['${sherpa}'])
vars.Save('.SConstruct',env)

if env['PLATFORM']=='darwin':
   env.Append( LINKFLAGS='-Wl,-undefined -Wl,dynamic_lookup' )

env.SharedLibrary('SherpaUserhookExample', ['Userhook_Example.C'])
