C Driver, to be modified by the user (keeping the read statements).
C Works only with Les Houches interface (so enter negative process numbers)
      SUBROUTINE MCCINT(PRNSET)
      LOGICAL PRNSET
      INCLUDE 'HERWIG65.INC'
      EXTERNAL HWUDAT
      INTEGER N,NSTEP,I,JPR
C QQIN IS THE EVENT FILE
      CHARACTER*50 QQIN
      COMMON/VVJIN/QQIN
      REAL*8 TMPLAM
      COMMON/CTMPLAM/TMPLAM
C
C      WRITE(*,*)'Enter filename for events'
C      READ(*,*)QQIN
C      WRITE(*,*)'Enter maximum number of events to generate'
C      WRITE(*,*)'MUST coincide with the number of events on tape'
C      READ(*,*)MAXEV
C      WRITE(*,*)'Enter 0 to use Herwig default PDFs'
C      WRITE(*,*)'      1 to use PDFs from library'
C      READ(*,*)IPDF
C OUTPUT THE RESULTS AFTER ANY NSTEP EVENTS
      NSTEP=20000
C---INITIALISE OTHER COMMON BLOCKS
      CALL HWIGIN
C---USER CAN RESET PARAMETERS AT
C   THIS POINT, OTHERWISE DEFAULT
C   VALUES IN HWIGIN WILL BE USED.
      PRNDEF=.FALSE.
      IF (PRNSET) PRNDEF=.TRUE.
C LHSOFT=.FALSE. SWITCHES UNDERLYING EVENT OFF
      LHSOFT=IPROC.GT.10000
      WRITE(*,*)
      IF (LHSOFT) THEN
         WRITE(*,*)'Underlying event WILL be generated'
      ELSE
         WRITE(*,*)'Underlying event WILL NOT be generated' 
      ENDIF
      WRITE(*,*)
C      WRITE(*,*) IBRN(1),IBRN(2)
C Select W/Z boson decay modes
C      MODBOS(1)=4
C      MODBOS(2)=3
C      IF(IPDF.EQ.1)THEN
C         DO I=1,2
C            WRITE(*,*)'   Incoming particle # ',I
C            WRITE(*,*)'Enter PDF group name (AUTPDF)'
C            READ(*,*)AUTPDF(I)
C            WRITE(*,*)'Enter PDF set number (MODPDF)'
C            READ(*,*)MODPDF(I)
C         ENDDO
C      ENDIF
C      WRITE(*,*)'Enter Lambda_QCD, <0 for Herwig default'
C      READ(*,*)TMPLAM
      IF(TMPLAM.GE.0.D0)QCDLAM=TMPLAM
C---CHECK PROCESS CODE
      JPR=MOD(ABS(IPROC),10000)/100
      IF (JPR.EQ.13.OR.JPR.EQ.14.OR.JPR.EQ.28) THEN
C         WRITE(*,*)'Enter W+, W-, Z0 masses'
C         READ(*,*)RMASS(198),RMASS(199),RMASS(200)
      ELSEIF (JPR.EQ.16) THEN
C         WRITE(*,*)'Enter Higgs boson and top masses'
C         READ(*,*)RMASS(201),RMASS(6)
      ELSEIF (JPR.EQ.17) THEN
         IF(ABS(IPROC).EQ.1705.OR.ABS(IPROC).EQ.11705)THEN
C           WRITE(*,*)'Enter bottom mass'
C           READ(*,*)RMASS(5)
         ELSEIF(ABS(IPROC).EQ.1706.OR.ABS(IPROC).EQ.11706)THEN
C           WRITE(*,*)'Enter top mass'
C           READ(*,*)RMASS(6)
         ENDIF
      ELSE
C         WRITE(*,*)'   Bad process code IPROC =',IPROC
C         CALL HWWARN('HWIGPR',502,*999)
      ENDIF
C      WRITE(*,*)'Enter quark (d,u,s,c,b) and gluon masses'
C      READ(*,*)RMASS(1),RMASS(2),RMASS(3),
C     #         RMASS(4),RMASS(5),RMASS(13)
      DO I=1,5
         RMASS(I+6)=RMASS(I)
      ENDDO
C NO SOFT ME CORRECTIONS (ALREADY INCLUDED IN MC@NLO)
      IF(IPROC.LT.0)THEN
        SOFTME=.FALSE.
      ELSE
        SOFTME=.TRUE.
      ENDIF
C HERWIG RUNS IN WEIGHTED MODE
      NOWGT=.FALSE.
C NEGATIVE WEIGHTS ALLOWED
      NEGWTS=.TRUE.
C      MAXPR=2
      MAXER=MAXEV/100
      LRSUD=0
      LWSUD=77
C IN THE CASE HERWIG PDFS ARE USED, ADOPT MRST
      NSTRU=8
      PRVTX=.FALSE.
      PTMIN=0.5
      NRN(1)=1973774260
      NRN(2)=1099242306
C THE FOLLOWING SHOULD BE IRRELEVANT (ONLY USED IN UNWEIGHTED MODE)
      WGTMAX=1.000001D0
      AVABW=1.000001D0
C FOR TOP PRODUCTION (HARMLESS ELSEWHERE)
      RLTIM(6)=1.D-23
      RLTIM(12)=1.D-23
C---B FRAGMENTATION PARAMETERS (FOR B PRODUCTION ONLY)
      IF(ABS(IPROC).EQ.1705.OR.ABS(IPROC).EQ.11705)THEN
        PSPLT(2)=0.5
      ENDIF
C---COMPUTE PARAMETER-DEPENDENT CONSTANTS
      CALL HWUINC
C---CALL HWUSTA TO MAKE ANY PARTICLE STABLE
C      CALL HWUSTA('PI0     ')
C---USER'S INITIAL CALCULATIONS
      CALL HWABEG
C---INITIALISE ELEMENTARY PROCESS
      CALL HWEINI
      RETURN
      END
c
c
c
c
C---SINGLE EVENT GENERATION
      SUBROUTINE MCCGSE
C---INITIALISE EVENT
      CALL HWUINE
C---GENERATE HARD SUBPROCESS
      CALL HWEPRO
C---GENERATE PARTON CASCADES
      CALL HWBGEN
C---DO HEAVY OBJECT DECAYS
      CALL HWDHOB
C---DO CLUSTER FORMATION
      CALL HWCFOR
C---DO CLUSTER DECAYS
      CALL HWCDEC
C---DO UNSTABLE PARTICLE DECAYS
      CALL HWDHAD
C---DO HEAVY FLAVOUR HADRON DECAYS
      CALL HWDHVY
C---ADD SOFT UNDERLYING EVENT IF NEEDED
      CALL HWMEVT
C---FINISH EVENT
      CALL HWUFNE
C---USER'S EVENT ANALYSIS
C      CALL HWANAL
C      IF(MOD(NEVHEP,NSTEP).EQ.0) THEN
C         WRITE(*,*)'# of events processed=',NEVHEP
C         CALL HWAEND
C      ENDIF
      RETURN
      END
c
c
c
c
c
C---TERMINATE ELEMENTARY PROCESS
      SUBROUTINE MCCTRM
C---TERMINATE ELEMENTARY PROCESS
      CALL HWEFIN
C---USER'S TERMINAL CALCULATIONS
      CALL HWAEND
      RETURN
      END
