C---HERWIG 6
      SUBROUTINE HWCINT() 
C---COMMON BLOCKS ARE INCLUDED AS FILE HERWIG65.INC
      INCLUDE 'HERWIG65.INC'
      EXTERNAL HWUDAT
C---INITIALISE OTHER COMMON BLOCKS
      CALL HWIGIN
C---COMPUTE PARAMETER-DEPENDENT CONSTANTS
      CALL HWUINC
C---CALL HWUSTA TO MAKE ANY PARTICLE STABLE
C      CALL HWUSTA('PI0     ')
C---USER'S INITIAL CALCULATIONS
      CALL HWABEG
C---INITIALISE ELEMENTARY PROCESS
      CALL HWEINI
      RETURN
      END


C---SINGLE EVENT GENERATION
      SUBROUTINE HWCGSE
C---INITIALISE EVENT
      CALL HWUINE
C---GENERATE HARD SUBPROCESS
      CALL HWEPRO
C---GENERATE PARTON CASCADES
      CALL HWBGEN
C---DO HEAVY OBJECT DECAYS
      CALL HWDHOB
C---DO CLUSTER FORMATION
      CALL HWCFOR
C---DO CLUSTER DECAYS
      CALL HWCDEC
C---DO UNSTABLE PARTICLE DECAYS
      CALL HWDHAD
C---DO HEAVY FLAVOUR HADRON DECAYS
      CALL HWDHVY
C---ADD SOFT UNDERLYING EVENT IF NEEDED
      CALL HWMEVT
C---FINISH EVENT
      CALL HWUFNE
      RETURN
      END



C---TERMINATE ELEMENTARY PROCESS
      SUBROUTINE HWCTRM
      CALL HWEFIN
C---USER'S TERMINAL CALCULATIONS
      CALL HWAEND
      STOP
      END

      SUBROUTINE HWPRINT
      CALL HWUEPR
      RETURN
      END

C---DUMMY ROUTINES
      SUBROUTINE HWABEG
      RETURN
      END
      SUBROUTINE HWAEND
      RETURN
      END
