#!/bin/bash
# 
# To successfully employ this script, make sure that your bash is in
# the bin - directory or adjust accordingly.
#

print_help(){
  echo "makelibs version 1.0" && echo && \
  echo "options: -c             \"make clean\" before compiling" && \
  echo "         -o             install single process module" && \
  echo "         -s <envfile>   set environment settings file to <envfile>" && \
  echo "         -n <name>      set job file name <name>" && \
  echo "         -g <option>    define job submit option <option>" && \
  echo "         -G <option>    define jdl file option <option>" && \
  echo "         -h             display this help and exit" && echo
}

ENVFILE=""
JOBFILE="submit_jobs"
while getopts :cos:n:g:G:h OPT
do
  case $OPT in
  c) CLEAN=TRUE ;; 
  o) ONE=TRUE ;;
  s) ENVFILE=$OPTARG ;;
  n) JOBFILE=$OPTARG ;; 
  g) EDGOPTS=$EDGOPTS" "$OPTARG ;; 
  G) GMISC=`echo -e "$GMISC\n$OPTARG"` ;;
  h) print_help && exit 0 ;;
  \?)
    shift `expr $OPTIND - 1`
    if [ "$1" = "--help" ]; then print_help && exit 0;
    else 
      echo -n "makelibs: error: unrecognized option "
      if [ $OPTARG != "-" ]; then echo "'-$OPTARG'. try '-h'"
      else echo "'$1'. try '-h'"
      fi
      print_help && exit 1
    fi
    shift 1
    OPTIND=1
  esac
done

DIRS=`find Process -name P?_?`" "`find Process -name P?_??`

if [ "$ONE" = "TRUE" ] ; then 
  echo "makelibs: select module ( q) to quit )"
  select DIRS in $DIRS ; do
    if [ "$DIRS" != "" ] ; then 
      SINGLE="TRUE"
      break
    else 
      if [ "$REPLY" = "q" ] || [ "$REPLY" = "Q" ]  ; then exit ; fi
    fi
  done
fi

chmod -R ugo+rwX $DIRS

SCR=$PWD"/"$JOBFILE
echo -e "#!/bin/bash\n\nSLF=\$PWD\"/"$JOBFILE".log\"" > $SCR
echo -e "submit(){\n  cd \$1\n  for I in *.jdl; do" >> $SCR
echo "    $EDGOPTS \$I >> \$SLF 2>&1" >> $SCR
echo -e "  done\n  cd -\n}\n" >> $SCR
for J in $DIRS ; do
  echo "======================"
  echo "$J";
  echo "======================"
  cd $J
  libtoolize --force
  aclocal
  automake -a
  autoconf
  ./configure
  if `test "$CLEAN" = "TRUE"` ; then make clean ; fi
  for I in P?_* fsrchannels*; do
    if echo $I | awk '{ if (match($0,"\\.")>0) exit(1); }'; then
      SFL=$I".sh"
      echo -e "#!/bin/bash\n" > $SFL
      echo -e "umask 0\n" >> $SFL
      if ! test -z "$ENVFILE"; then echo -e "source $ENVFILE\n" >> $SFL; fi
      echo -e "cd $PWD/$I\n" >> $SFL
      echo -e "if make install; then make clean; fi >> $PWD/$I.log 2>&1\n" >> $SFL
      chmod ugo+rx $SFL
      JFL=$I".jdl"
      echo "Executable = \"$SFL\";" > $JFL
      echo "RetryCount = 0; ShallowRetryCount = 0;" >> $JFL
      echo "StdOutput = \"run.out\"; StdError = \"run.err\";" >> $JFL
      echo "OutputSandbox = {}; InputSandbox = {\"$SFL\"};" >> $JFL
      echo "$GMISC" >> $JFL
      chmod ugo+r $JFL
    fi
  done
  echo "submit $J" >> $SCR
  cd -
done
chmod ugo+rx $SCR
echo -e "makelibs: \033[1mexecute '\033[31m./"$JOBFILE"\033[0m\033[1m'\
 to submit compile jobs.\033[0m"
