[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ufo_interface"
version = "3.0.0"
description = "UFO parser for Sherpa"
readme = "README.md"
dependencies = ["sympy", "numpy", "opt_einsum"]

[project.scripts]
Sherpa-generate-model = "ufo_interface.parser:main"

[tool.setuptools]
package-data = {"ufo_interface" = ["Templates/*"]}
