#!/bin/bash

FILES=*.orig

for I in $FILES; do
  FN=`echo $I | awk '{match($0,".orig");printf substr($0,0,RSTART-1)}'`
  awk 'BEGIN{ pi=3.141592654; }{ if ($1=="#") { print $0; } \
         else if (NF>0) { \
         printf "%6.5f\t%6.5e\t%6.5f\t%6.5f\t%6.5e\t%6.5e\n", \
                $3,$4,$3-$1/128*pi,$2/128*pi-$3,$5+$7,$6+$8; }}' < $I > $FN
done
