#ifndef Data_To_Function_inl_H
#define Data_To_Function_inl_H

#include "Data_To_Function.H"

using namespace ATOOLS;

namespace ATOOLS {


  template <class Argument_Type,class Result_Type>
  Argument_Type Data_To_Function<Argument_Type,Result_Type>::DeltaXMax()

  template <class Argument_Type,class Result_Type>
  Argument_Type Data_To_Function<Argument_Type,Result_Type>::DeltaXMin()

  template <class Argument_Type,class Result_Type>
  Result_Type Data_To_Function<Argument_Type,Result_Type>::DeltaYMax()

  template <class Argument_Type,class Result_Type>
  Result_Type Data_To_Function<Argument_Type,Result_Type>::DeltaYMin()

} // end of namespace ATOOLS

#endif
