#!/usr/bin/python

import os
import getpass
import time

import BeamBox
import PDFBox
import ProcessBox



class ParameterBox():
    def __init__(self):
        print "Initialising ParameterBox."
        self.beambox = BeamBox.BeamBox()
        self.pdfbox  = PDFBox.PDFBox()
        #self.procbox = ProcessBox.ProcessBox()
        self.initialiseDefaults()

    def initialiseDefaults(self):
        print "Initialise defaults in the ParameterBox."
        self.beambox.initialiseDefaults()
        self.pdfbox.initialiseDefaults(self.beambox.getCollider())
        #self.procbox.initialiseDefaults(self.beambox.getCollider())

    def printDefaults(self):
        self.beambox.printDefaults()
        self.pdfbox.printDefaults()

    def updateBeams(self,collider_tag):
        print "In updateBeams(",collider_tag,")"
        self.beambox.setCollider(collider_tag)
        self.pdfbox.initialiseDefaults(self.beambox.getCollider())
        #self.procbox.initialiseDefaults(self.beambox.getCollider())

    def getBeamBox(self):
        return self.beambox

    def getPDFBox(self):
        return self.pdfbox

    def getProcBox(self):
        return self.procbox

    def write(self):
        filename   = "Run.dat"
        username   = getpass.getuser()
        timestring = time.strftime("%a, %d %b %Y %H:%M:%S +0000",time.gmtime()) 
        runfile = open(filename,"w")
        runfile.write('%%% Card generated by '+username+', '+timestring+'\n')
        self.write_general(runfile)
        self.beambox.write(runfile)
        self.pdfbox.write(runfile,self.beambox.getCollider())
        #self.procbox.write(runfile)

    def write_general(self,runfile):
        #totjets = self.procbox.totjets
        #nlojets = self.procbox.nlojets
        runfile.write('  NJETS:=%i;NLOJETS:=%i;\n' %(totjets,nlojets))
        runfile.write('\n')
        runfile.write('ME_SIGNAL_GENERATORS = Comix, Amegic')
        #if self.procbox.isNLO():
        #    runfile.write(', Internal, LOOPGEN\n')
        #    runfile.write('NLO_Mode = 3;\n')
        #else:
        #    runfile.write('\n')
        runfile.write('\n')
        runfile.write('SCALES METS{SCF2*MU_F2}{SCR2*MU_R2}{SCQ2*MU_Q2}\n\n')


if __name__ == "__main__":
    pbox = ParameterBox()
    pbox.printDefaults



