#!/usr/bin/python

import os
import getpass
import time

import BeamBox
import PDFBox
import ProcessBox


class ParameterBox():
    def __init__(self):
        print "Initialising ParameterBox."
        self.beambox = BeamBox.BeamBox()
        self.pdfbox  = PDFBox.PDFBox()
        self.procbox = ProcessBox.ProcessBox()
        self.initialiseDefaults()

    def initialiseDefaults(self):
        print "Initialise defaults in the ParameterBox."
        self.beambox.initialiseDefaults()
        self.pdfbox.initialiseDefaults(self.beambox.getCollider())
        self.procbox.initialiseDefaults(self.beambox.getCollider())

    def printStatus(self):
        self.beambox.printStatus()
        self.pdfbox.printStatuss()

    def updateBeams(self,collider_tag):
        print "In updateBeams(",collider_tag,")"
        self.beambox.setCollider(collider_tag)
        self.pdfbox.initialiseDefaults(self.beambox.getCollider())
        self.procbox.initialiseDefaults(self.beambox.getCollider())

    def getBeamBox(self):
        return self.beambox

    def getPDFBox(self):
        return self.pdfbox

    def getProcBox(self):
        return self.procbox

    def write(self,genstring):
        filename   = "Run.dat"
        runfile = open(filename,"w")
        self.write_general(runfile)
        self.beambox.write(runfile)
        self.pdfbox.write(runfile,self.beambox.getCollider())
        self.procbox.write(runfile)

    def write_general(self,runfile):
        username   = getpass.getuser()
        timestring = time.strftime("%a, %d %b %Y %H:%M:%S +0000",time.gmtime()) 
        runfile.write("%%% Card generated by "+username+", "+timestring+"\n")
        totjets, nlojets = self.procbox.getNJets()
        runfile.write("  NJETS:={}; NLOJETS:={};\n".format(totjets,nlojets))
        muF2,muR2,muQ2   = self.procbox.getScaleFactors() 
        runfile.write("  SF2:=%.2f; SR2:=%.2f; SQ2:=%.2f;\n" %(muF2,muR2,muQ2))
        runfile.write("\n")
        loopstring = ""
        if nlojets>-1:
            gens = self.procbox.getLoopGens()
            if gens!=None and len(gens)>-1:
                for n in range(0,len(gens)):
                    if gens[n]!="None":
                        loopstring=loopstring+str("LOOPGEN%s, " %str(n))
                        print ("LOOPGEN%s:=%s" %(str(n),gens[n]))
                        runfile.write("LOOPGEN%s:=%s\n" %(str(n),gens[n]))
            runfile.write("NLO_Mode = 3;\n")

        runfile.write("ME_SIGNAL_GENERATORS = Comix, Amegic\n\n")
        runfile.write("SCALES METS{SCF2*MU_F2}{SCR2*MU_R2}{SCQ2*MU_Q2}\n\n")



