#ifndef METOOLS_HadronCurrents_Rho_Decays_H
#define METOOLS_HadronCurrents_Rho_Decays_H

#include "METOOLS/HadronCurrents/Resonance_Base.H"

namespace METOOLS {
  class Rho_770_0_Lineshape : public Total_Width_Base {
  public:
    Rho_770_0_Lineshape();
  };

  class Rho_770_plus_Lineshape : public Total_Width_Base {
  public:
    Rho_770_plus_Lineshape();
  };

  class Rho_1450_0_Lineshape : public Total_Width_Base {
  public:
    Rho_1450_0_Lineshape();
  };

  class Rho_1450_plus_Lineshape : public Total_Width_Base {
  public:
    Rho_1450_plus_Lineshape();
  };

  class Rho_1700_0_Lineshape : public Total_Width_Base {
  public:
    Rho_1700_0_Lineshape();
  };

  class Rho_1700_plus_Lineshape : public Total_Width_Base {
  public:
    Rho_1700_plus_Lineshape();
  };
}

#endif
