#!/bin/sh

FILES=`find -maxdepth 2 -name ".*.dat.old"`  # find files ./.<name>.dat.old    
for I in $FILES; do                         # for all files
  DIRECTORY=`echo $I | cut -d "." -f 2,3,4 --complement`
  FILENAME=`echo $I | cut -d "." -f 2,3,4`
  echo "rename $I to $DIRECTORY$FILENAME"
  mv $I $DIRECTORY/$FILENAME                            # rename file
done  
