#!/bin/bash

FILES=*.orig

for I in $FILES; do
  FN=`echo $I | awk '{match($0,".orig");printf substr($0,0,RSTART-1)}'`
  awk '{ if ($1=="#") { print $0; } \
         else if (NF>0) { m=($1+$2)/2.0; \
         printf "%4.1f\t%4.3e\t%4.1f\t%4.1f\t%4.3e\t%4.3e\n", \
                m,$3,m-$1,$2-m,$4+$6/100*$3,$5+$7/100*$3; }}' < $I > $FN
done
