CDECK  ID>, VISAJE. 
      CHARACTER*40 FUNCTION VISAJE()
      COMMON/IDRUN/IDVER,IDG(2),IEVT,IEVGEN
      SAVE /IDRUN/
      INTEGER   IDVER,IDG,IEVT,IEVGEN
      VISAJE = ' ISAJET     V7.67   28-APR-2003 19:26:11'
      IDVER = 767
      RETURN
      END
