#!/usr/bin/env python3
"""Generate the run cards for the FCC-ee threshold YFS WW correction budget.

The ladder is six rungs in four runs, because YFS: Ladder_Weights emits two of
them as exactly-correlated named weights on a single sample (see
YFS_Handler::BuildLadderWeights). The master run carries ISR+FSR+IFI+Coulomb as
its nominal and ships

    YFS.NoCoulomb  x  -> drop Coulomb          (the L3 rung)
    YFS.NoIFI      x  -> drop the IF form factor (the IFI_Sub: 0 run, L2)

so L2 and L3 are columns of one sample rather than two productions. Born and
ISR-only need their own runs because those change what the generator produces
rather than how the event is weighted.

There is no WW-form-factor rung here. It used to be YFS.WWForm, built from
BVV_WW, which omits the initial-initial pair and so is not free of the photon
mass -- that column came out ~3300x the nominal. Its replacement is the
YFS: WW_Scheme: pole dipole expansion, which is implemented and gives correct
exponents (the production-stage interference cancels to 0.4%, the Gamma_W/M_W
suppression) but whose crude-weight bookkeeping for a dipole made of W's is not
finished, so it is not part of this production. Left at the default, flat.

Usage:  make-cards.py [outdir]      (default: ./generated)
"""
import os, sys

# --- scan points -----------------------------------------------------------
# The FCC-ee W-mass threshold scan. 161 is the point of maximum dsigma/dm_W;
# the other two bracket it and are where the scan actually spends its
# luminosity.
ENERGIES = [157.5, 161.0, 162.5]

# --- channels --------------------------------------------------------------
# Different-flavour leptonic WW: W- -> l1- nubar_l1, W+ -> l2+ nu_l2, l1 != l2,
# both charge assignments. Written as (tag, final state) with the final state
# in the order (l1-, nubar_l1, l2+, nu_l2).
CHANNELS = [
    ("mue",  "13 -14 -11 12"),
    ("emu",  "11 -12 -13 14"),
    ("mutau","13 -14 -15 16"),
    ("taumu","15 -16 -13 14"),
    ("etau", "11 -12 -15 16"),
    ("taue", "15 -16 -11 12"),
]

# --- m_W variation ---------------------------------------------------------
# EW_SCHEME defaults to Gmu, in which m_W is an input and sin^2(theta_W) and
# alpha are derived from it -- so overriding the W mass here is a consistent
# SM variation, not just a propagator shift. +/-100 MeV is wide enough that the
# finite difference is not MC noise and narrow enough to stay linear.
MW_NOMINAL = 80.379
# The three symmetric points give dsigma/dm_W by central difference. 80.4335 is
# the CDF II value (80433.5 +- 9.4 MeV), and it is here as a CHECK rather than
# as a scan point: it sits at +54.5 MeV, inside the +-100 MeV bracket, so the
# three-point derivative predicts its cross section. Comparing that prediction
# against the direct run tests the linear response that every delta-m_W number
# in the budget is converted through -- an assumption otherwise taken on faith.
MW_VARIATIONS = [80.279, 80.379, 80.479, 80.4335]

BASE = """# Generated by cards/make-cards.py -- do not edit by hand.
# {title}
BEAMS: [11, -11]
BEAM_ENERGIES: {ehalf!r}

ALPHAS(MZ): 0.1188
ORDER_ALPHAS: 1
BEAM_REMNANTS: None
FRAGMENTATION: None
SHOWER_GENERATOR: None
SCALES: VAR{{E_CMS*E_CMS}}
PDF_LIBRARY: None

# PHOTONS++ off, explicitly, on every rung. Sherpa only disables it by itself
# when YFS is active (Signal_Process_FS_QED_Correction.C: "Force Photons++ to
# be off if YFS ISR is switched on"), so the one card with no YFS: block --
# L0_born, the Born reference the whole ladder is divided by -- otherwise picks
# up the default ME_QED handler and is silently NOT bare Born: it carries
# PHOTONS++ final-state radiation, its photon spectrum is not empty, and photon
# splitting there makes extra charged leptons that the Rivet analysis then
# vetoes (measured: acceptance 0.9958 instead of 1). Set here rather than in the
# L0 block alone so a future rung without a YFS: block cannot reintroduce it.
ME_QED:
    ENABLED: false

# Nothing in this study needs unweighted events, and the unweighting efficiency
# on this process is 0.07-0.7% -- measured, L6 goes from 456 to 413000
# events/day and from 57.7% to 12.2% error on sigma in a fifth of the wall time.
EVENT_GENERATION_MODE: Weighted

PARTICLE_DATA:
    11:
        Massive: true
    13:
        Massive: true
    15:
        Massive: true
        # Stable so the tau channels measure WW radiation and not tau decay:
        # the study is about the photon field around the W pair, and a decaying
        # tau would bury it under decay products.
        Stable: 1
{mwblock}
{yfsblock}
PROCESSES:
- 11 -11 -> {fs}:
    Order: {{QCD: 0, EW: 4}}
{procextra}
# Generator-level cuts, IDENTICAL on every rung and every channel, so the cross
# sections stay comparable -- that requirement is what "no SELECTORS" used to
# protect, and a common cut protects it equally.
#
# These are a REGULATOR, not the acceptance. The acceptance still lives in
# Rivet (LEPCOS 0.95 = 18.2 deg, LEPE 10 GeV), and these cuts are deliberately
# looser than it, so the fiducial results are not biased by their own boundary.
#
# Why they are needed. Run cut-free, the four channels with an electron in the
# final state carry non-resonant single-W / t-channel-photon diagrams in which
# the final-state e+- goes collinear to the beam. That region is integrably
# singular, and measured on 2M-event samples it does two things:
#
#   * sigma(e-channel) came out ~40% ABOVE the electron-free channels
#     (mue 0.0735 pb vs mutau 0.0517 pb at 161 GeV) -- i.e. the "WW" cross
#     section was not mostly WW.
#   * rare enormous weights: one seed in four read 1.2-2.5% error where its
#     siblings read 0.07-0.15%, and its central value sat up to 2.4% high.
#     rivet-merge combines seeds by sumW, not by inverse variance, so that seed
#     dragged the merged number with it -- ~16 MeV in m_W at 162.5 GeV.
#
# The electron-free channels (mutau, taumu) need none of this: four seeds there
# agreed to four decimals at 0.07%. The cut is applied to all charged leptons
# anyway so that all six channels share one phase-space definition; on the
# muon and tau channels it removes almost nothing.
#
# 10 deg / 5 GeV rather than something tighter: it has to sit well inside the
# Rivet acceptance, or the generator cut and not the physics would be setting
# the fiducial cross section.
SELECTORS:
- [Polar_Angle, 11, 10.0, 170.0, 0]
- [Polar_Angle, -11, 10.0, 170.0, 0]
- [Polar_Angle, 13, 10.0, 170.0, 0]
- [Polar_Angle, -13, 10.0, 170.0, 0]
- [Polar_Angle, 15, 10.0, 170.0, 0]
- [Polar_Angle, -15, 10.0, 170.0, 0]
- [E, 11, 5.0, E_CMS]
- [E, -11, 5.0, E_CMS]
- [E, 13, 5.0, E_CMS]
- [E, -13, 5.0, E_CMS]
- [E, 15, 5.0, E_CMS]
- [E, -15, 5.0, E_CMS]

ANALYSIS: Rivet

RIVET:
    IGNORE_BEAMS: 1
    ANALYSES:
        # Bare name, no `yfs-ww:OPT=value`. Rivet accepts that syntax but
        # folds the option string into the analysis NAME, so every histogram
        # path becomes /yfs-ww:OPT=value/... and scripts/check-yoda.py, which
        # reads /yfs-ww/xs and treats its absence as "the analysis did not
        # run", fails every card. The selection values therefore live as
        # defaults in yfs-ww.cc -- PTMISS_EBEAM (p_T^miss/E_beam, OPAL's
        # acoplanar-dilepton selection hep-ex/9909052, a ratio so one number
        # covers all three scan energies) and ACOL_MAX (off: LEP experiments
        # used anything from 20 to 165 degrees, so any default here would be
        # an arbitrary choice dressed up as a convention).
        - yfs-ww
"""

MW_BLOCK = """    24:
        Mass: {mw}
"""

RUNGS = {
 # Born. No YFS block at all -- the fixed-order reference the whole ladder is
 # measured against.
 "L0_born": dict(
    title="L0: Born, YFS off",
    yfs="",
    procextra=""),

 # ISR only. Separate run because it changes what is generated.
 "L1_isr": dict(
    title="L1: ISR only",
    yfs="""YFS:
    MODE: ISR
    FULL_FORM: 1
    Ladder_Weights: 1
    Dump_Dipoles: 1
""",
    procextra=""),

 # The master Born-level run. Nominal = ISR+FSR+IFI+Coulomb; L2 and L3 come off
 # it as named weights.
 "L4_master": dict(
    title="L4: ISR+FSR+IFI+Coulomb, with the ladder weights for L2/L3",
    yfs="""YFS:
    MODE: ISRFSR
    FULL_FORM: 1
    IFI_Sub: 1
    COULOMB: true
    Ladder_Weights: 1
    Dump_Dipoles: 1
""",
    procextra=""),

 # The LO baseline: L4 with the EEX beta expansion off. Born-level runs are
 # where BETA actually bites -- there the EEX sets m_real and nothing overwrites
 # it, so the default BETA:2 puts the leading-log higher-order series into the
 # nominal. This rung is the common reference that both higher-order treatments
 # are measured against:
 #     EEX (leading-log) = L4_master / L5_lo - 1
 #     NLO (exact)       = L6 nominal / YFS.LO - 1
 # They are alternatives, not successive rungs, and their difference is how well
 # the leading-log approximation reproduces the exact O(alpha).
 "L5_lo": dict(
    title="L5: LO baseline -- L4 with the EEX beta expansion off (BETA: 0)",
    yfs="""YFS:
    MODE: ISRFSR
    FULL_FORM: 1
    IFI_Sub: 1
    COULOMB: true
    BETA: 0
    Ladder_Weights: 1
""",
    procextra=""),

 # NLO matching on top of L4. NLO_Weight_Breakdown gives the matching and
 # photon-multiplicity truncations as further correlated columns.
 "L6_nlo": dict(
    title="L6: L4 + YFS NLO matching (BVR)",
    yfs="""YFS:
    MODE: ISRFSR
    FULL_FORM: 1
    IFI_Sub: 1
    COULOMB: true
    Ladder_Weights: 1
    NLO_Weight_Breakdown: 1
    # BETA left at its default 2 deliberately. In an NLO run it cannot reach the
    # nominal -- CalculateBeta sets m_real from the EEX series and the NLO block
    # then overwrites it -- and YFS.LO is built from w_lo, which is formed before
    # m_real is applied. Measured: every column is bit-identical between BETA 0
    # and 2 here except YFS.EEX, which is NaN at BETA:0 because m_eex is only
    # ever assigned inside `if (m_betaorder > 0)` and has no initialiser.
    Real_Generator: OpenLoops
    Integrate_NLO: 0
""",
    procextra="""    NLO_Mode: YFS
    NLO_Part: BVR
    NLO_Order: {EW: 1, QCD: 0}
    Loop_Generator: OpenLoops
"""),
}


def write(outdir, name, text):
    path = os.path.join(outdir, name)
    with open(path, "w") as f:
        f.write(text)
    return path


def main():
    outdir = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "generated")
    os.makedirs(outdir, exist_ok=True)
    written = []

    for rung, cfg in RUNGS.items():
        for e in ENERGIES:
            for tag, fs in CHANNELS:
                name = "%s_%s_%s.yaml" % (rung, str(e).replace(".", "p"), tag)
                written.append(write(outdir, name, BASE.format(
                    title=cfg["title"], ehalf=e/2., mwblock="",
                    yfsblock=cfg["yfs"], fs=fs, procextra=cfg["procextra"])))

    # dsigma/dm_W: ISR-only (cheap) at each scan point, mue channel only.
    # The nominal mass is regenerated here rather than reusing L1_isr so that
    # all three points of the finite difference come from cards that differ in
    # exactly one line.
    for e in ENERGIES:
        for mw in MW_VARIATIONS:
            name = "MW_%s_%s_mue.yaml" % (str(e).replace(".", "p"),
                                          str(mw).replace(".", "p"))
            written.append(write(outdir, name, BASE.format(
                title="dsigma/dm_W probe: ISR only, m_W = %s GeV" % mw,
                ehalf=e/2., mwblock=MW_BLOCK.format(mw=mw),
                yfsblock=RUNGS["L1_isr"]["yfs"], fs="13 -14 -11 12",
                procextra="")))

    print("wrote %d cards to %s" % (len(written), outdir))


if __name__ == "__main__":
    main()
