(initial){
  PIECE_SETUP hep-ex_9603010.C (DEtaCone){ }(DEtaCone);
  PIECE_SETUP hep-ex_9603010.C (CosDPhiCone){ }(CosDPhiCone);
  RIGHT_AXIS YES; TOP_AXIS YES;
  DEFINE_COLOURS VIOLET1 195 0 185,;
  DEFINE_COLOURS BLUE1 25 25 205,;
  DEFINE_COLOURS GREEN1 30 145 35,;
  DEFINE_COLOURS YELLOW1 240 215 10,;
  DEFINE_COLOURS RED1 195 15 15,;
  DEFINE_COLOURS BLUE2 15 20 180,;
  DEFINE_COLOURS GREEN2 15 125 25,;
  DEFINE_COLOURS YELLOW2 214 173 9,;
  DEFINE_COLOURS RED2 175 5 5,;
  Y_TITLE_OFFSET 1.4;
  LEFT_MARGIN 0.15;
}(initial);

(DEtaCone){
  PIECE_SETUP hep-ex_9603010.C (paths){ }(paths);
  FILE_PIECE BFKL_DEta_ConeJetsPTY.dat;
  DRAW YES;
  X_MIN 0; X_MAX 6; Y_MIN 1e+2; Y_MAX 1e+6;
  Y_SCALING Log_B_10;
  // ## RESIZE_BINS -4 2,;
  HISTOGRAM_NAME BFKL_DEta;
  WEBPAGE_CAPTION &Delta\;&eta\;;
}(DEtaCone);

(CosDPhiCone){
  PIECE_SETUP hep-ex_9603010.C (dpaths){ }(dpaths);
  PIECE_SETUP hep-ex_9603010.C (dpathsd){ }(dpathsd);
  FILE_PIECE CosDPhi_vs_DEta_ConeJetsPTY.dat;
  X_MIN 0; X_MAX 5.3; 
  @@ YMIN 0.601; @@ YMAX 1.0; @@ DYMIN -0.099; @@ DYMAX 0.099;
  CANVAS_HEIGHT 400; LEG_DELTA_Y 0.05;  @@ SFAC 25;
  X_AXIS_TITLE #Delta#eta; Y_AXIS_TITLE <cos(#pi-#Delta#phi)>;
  @@ RPARAM ADOPT_BINS ./D0_Data/CosDPhi_vs_DEta_ConeJetsPTY.dat;
  HISTOGRAM_NAME CosDPhi_vs_DEta_ConeJets;
  WEBPAGE_CAPTION &lt\;cos(&pi\;-&Delta\;&phi\;)&gt\; vs. &Delta\;&eta\;;
}(CosDPhiCone);

(paths){
  PIECE_SETUP hep-ex_9603010.C (PD[1[+1]2]){ }(PD[1[+1]2]);
  PIECE_SETUP hep-ex_9603010.C (P[1[+1]2]){ }(P[1[+1]2]);
  @@ SFAC 1;
}(paths);
(dpaths){
  PIECE_SETUP hep-ex_9603010.C (PD[1[+1]2]){ }(PD[1[+1]2]);
  PIECE_SETUP hep-ex_9603010.C (P[1[+1]2]){ }(P[1[+1]2]);
  BOTTOM_MARGIN 0.3; X_AXIS_LABEL_SIZE 0; X_TITLE_SIZE 0;
  DRAW YES; Y_MIN YMIN; Y_MAX YMAX;
  DRAW_LATEX parton level | COLOUR 2 SIZE 0.04 LEFT 0.075 TOP 0.125 ALIGN 11,;
  DRAW_LATEX SHERPA | SIZE .04 COLOUR 19 LEFT .05 TOP .05 ALIGN 11 PRIORITY -10,;
  if (DDISC==true) {
    DRAW_LATEX KT Jets | COLOUR 4 SIZE 0.04 LEFT 0.15 TOP 0.9 ALIGN 13,;
    DRAW_LATEX For cross check only ! | COLOUR 16 SIZE 0.065 LEFT 0.5 TOP 0.5 ALIGN 22 ANGLE 35 PRIORITY -20,;
  }
}(dpaths);
(dpathsd){
  PIECE_SETUP hep-ex_9603010.C (PDPD[1[+1]2]){ }(PDPD[1[+1]2]);
  PIECE_SETUP hep-ex_9603010.C (PDPDB[1[+1]2]){ }(PDPDB[1[+1]2]);
  PIECE_SETUP hep-ex_9603010.C (PDP[1[+1]2]){ }(PDP[1[+1]2]);
  DIFF_PLOT YES; TOP_MARGIN 0.7; Y_TITLE_SIZE 0;
  DRAW YES; Y_MIN DYMIN; Y_MAX DYMAX;
  DRAW_LINE H 0 COLOUR 1 STYLE 1 PRIORITY -3,; 
  Y_AXIS_TICK_LENGTH 0.08; Y_AXIS_NDIVISIONS 000505;
  DRAW_LEGEND NO; ## ALLOW_MISSING NO;
  DRAW_LATEX Theory/Data-1 | COLOUR 1 SIZE 0.03 LEFT 0.05 TOP 0.85 ALIGN 13,;
}(dpathsd);
(PD1){
  PIECE_SETUP hep-ex_9603010.C (jets){ }(jets);
  PATH_PIECE D0_Data/Stat/; DATA_TYPE ASCII; 
  DRAW_OPTION P; LINE_COLOUR 1; MARKER_COLOUR 1;
  DRAW_PRIORITY 20;
  X_VALUE 1; Y_VALUE 2;
  X_ERROR_MINUS 3; X_ERROR_PLUS 4;
  Y_ERROR_MINUS 5; Y_ERROR_PLUS 6;
  LEGEND_TITLE D0 Data; ## DISALLOW_RESCALE YES;
}(PD1);
(PD2){
  PIECE_SETUP hep-ex_9603010.C (jets){ }(jets);
  PATH_PIECE D0_Data/; DATA_TYPE ASCII; 
  DRAW_OPTION P; LINE_COLOUR 1; MARKER_COLOUR 1;
  DRAW_PRIORITY 20;
  X_VALUE 1; Y_VALUE 2;
  X_ERROR_MINUS 3; X_ERROR_PLUS 4;
  Y_ERROR_MINUS 5; Y_ERROR_PLUS 6;
  DRAW_LEGEND NO; ## DISALLOW_RESCALE YES;
}(PD2);
(PDPDB1){
  PATH_PIECE D0_Data/;
  Y_FUNCTION 0|dy/y; DRAW_PRIORITY -5;
  X_VALUE 1; Y_VALUE 2;
  X_ERROR_MINUS 3; X_ERROR_PLUS 4;
  Y_ERROR_MINUS 5; Y_ERROR_PLUS 6;
  DRAW_OPTION P2; FILL_COLOUR 5; MARKER_SIZE 0;
}(PDPDB1);
(PDPDB2){
  PATH_PIECE D0_Data/Stat/;
  Y_FUNCTION 0|dy/y; DRAW_PRIORITY -5;
  X_VALUE 1; Y_VALUE 2;
  X_ERROR_MINUS 3; X_ERROR_PLUS 4;
  Y_ERROR_MINUS 5; Y_ERROR_PLUS 6;
  DRAW_OPTION P2; FILL_COLOUR YELLOW1; MARKER_SIZE 0;
}(PDPDB2);
(PDPD1){
  PATH_PIECE D0_Data/;
  Y_FUNCTION 0|dy/y;
  X_VALUE 1; Y_VALUE 2;
  X_ERROR_MINUS 3; X_ERROR_PLUS 4;
  Y_ERROR_MINUS 5; Y_ERROR_PLUS 6;
  DRAW_OPTION P; MARKER_COLOUR 12; LINE_COLOUR 12;
  DRAW_PRIORITY 5;
  DRAW_LINES H 0 | STYLE 1 COLOUR 1,;
}(PDPD1);
(PDPD2){
  PATH_PIECE D0_Data/Stat/;
  Y_FUNCTION 0|dy/y;
  X_VALUE 1; Y_VALUE 2;
  X_ERROR_MINUS 3; X_ERROR_PLUS 4;
  Y_ERROR_MINUS 5; Y_ERROR_PLUS 6;
  DRAW_OPTION P; MARKER_COLOUR 12; LINE_COLOUR 12;
  DRAW_PRIORITY 5;
  DRAW_LINES H 0 | STYLE 1 COLOUR 1,;
}(PDPD2);
(P1){
  PIECE_SETUP hep-ex_9603010.C (jets){ }(jets);
  PATH_PIECE BPATH1/;
  DATA_TYPE ATOOLS; ## RPARAM; Y_FUNCTION y/SFAC;
  LINE_COLOUR 2; LINE_STYLE 1;
  LEGEND_TITLE Comix #otimes CSS; 
}(P1);
(PDP1){
  PIECE_SETUP hep-ex_9603010.C (jets){ }(jets);
  PATH_PIECE D0_Data/ BPATH1/;
  DATA_TYPE ALGEBRA(y[1]/y[0]-1);
  LINE_COLOUR 2; LINE_STYLE 1;
}(PDP1);
(P2){
  PIECE_SETUP hep-ex_9603010.C (jets){ }(jets);
  PATH_PIECE BPATH2/;
  DATA_TYPE ATOOLS; ## RPARAM; Y_FUNCTION y/SFAC;
  LINE_COLOUR 4; LINE_STYLE 2;
  LEGEND_TITLE CSS only;
}(P2);
(PDP2){
  PIECE_SETUP hep-ex_9603010.C (jets){ }(jets);
  PATH_PIECE D0_Data/ BPATH2/;
  DATA_TYPE ALGEBRA(y[1]/y[0]-1);
  LINE_COLOUR 4; LINE_STYLE 2;
}(PDP2);
