#ifndef AddOns_HZTool_HZTool_Analyses_H
#define AddOns_HZTool_HZTool_Analyses_H

extern "C" {

  void hz00145_(int *);
  void hz00145(int flag) { hz00145_(&flag); }

  void hz01073_(int *);
  void hz01073(int flag) { hz01073_(&flag); }

  void hz00017_(int *);
  void hz00017(int flag) { hz00017_(&flag); }

  void hz00035_(int *);
  void hz00035(int flag) { hz00035_(&flag); }

  void hz00040_(int *);
  void hz00040(int flag) { hz00040_(&flag); }

  void hz00166_(int *);
  void hz00166(int flag) { hz00166_(&flag); }

  void hz00174_(int *);
  void hz00174(int flag) { hz00174_(&flag); }

//   void hz00181_(int *);
//   void hz00181(int flag) { hz00181_(&flag); }

//   void hz01064_(int *);
//   void hz01064(int flag) { hz01064_(&flag); }

  void hz01100_(int *);
  void hz01100(int flag) { hz01100_(&flag); }

  void hz01220_(int *);
  void hz01220(int flag) { hz01220_(&flag); }

  void hz01225_(int *);
  void hz01225(int flag) { hz01225_(&flag); }

  void hz02023_(int *);
  void hz02023(int flag) { hz02023_(&flag); }

  void hz02079_(int *);
  void hz02079(int flag) { hz02079_(&flag); }

  void hz02228_(int *);
  void hz02228(int flag) { hz02228_(&flag); }

  void hz03015_(int *);
  void hz03015(int flag) { hz03015_(&flag); }

  void hz03094_(int *);
  void hz03094(int flag) { hz03094_(&flag); }

  void hz03160_(int *);
  void hz03160(int flag) { hz03160_(&flag); }

  void hz94033_(int *);
  void hz94033(int flag) { hz94033_(&flag); }

  void hz94176_(int *);
  void hz94176(int flag) { hz94176_(&flag); }

  void hz95007_(int *);
  void hz95007(int flag) { hz95007_(&flag); }

  void hz95033_(int *);
  void hz95033(int flag) { hz95033_(&flag); }

  void hz95036_(int *);
  void hz95036(int flag) { hz95036_(&flag); }

  void hz95072_(int *);
  void hz95072(int flag) { hz95072_(&flag); }

  void hz95084_(int *);
  void hz95084(int flag) { hz95084_(&flag); }

  void hz95108_(int *);
  void hz95108(int flag) { hz95108_(&flag); }

  void hz95115_(int *);
  void hz95115(int flag) { hz95115_(&flag); }

  void hz95194_(int *);
  void hz95194(int flag) { hz95194_(&flag); }

  void hz95219_(int *);
  void hz95219(int flag) { hz95219_(&flag); }

  void hz95221_(int *);
  void hz95221(int flag) { hz95221_(&flag); }

//   void hz96039_(int *);
//   void hz96039(int flag) { hz96039_(&flag); }

//   void hz96076_(int *);
//   void hz96076(int flag) { hz96076_(&flag); }

  void hz96094_(int *);
  void hz96094(int flag) { hz96094_(&flag); }

  void hz96122_(int *);
  void hz96122(int flag) { hz96122_(&flag); }

  void hz96138_(int *);
  void hz96138(int flag) { hz96138_(&flag); }

  void hz96160_(int *);
  void hz96160(int flag) { hz96160_(&flag); }

  void hz96215_(int *);
  void hz96215(int flag) { hz96215_(&flag); }

  void hz97098_(int *);
  void hz97098(int flag) { hz97098_(&flag); }

  void hz97108_(int *);
  void hz97108(int flag) { hz97108_(&flag); }

  void hz97158_(int *);
  void hz97158(int flag) { hz97158_(&flag); }

  void hz97164_(int *);
  void hz97164(int flag) { hz97164_(&flag); }

  void hz97179_(int *);
  void hz97179(int flag) { hz97179_(&flag); }

  void hz97183_(int *);
  void hz97183(int flag) { hz97183_(&flag); }

  void hz97191_(int *);
  void hz97191(int flag) { hz97191_(&flag); }

  void hz97196_(int *);
  void hz97196(int flag) { hz97196_(&flag); }

  void hz97210_(int *);
  void hz97210(int flag) { hz97210_(&flag); }

  void hz98018_(int *);
  void hz98018(int flag) { hz98018_(&flag); }

  void hz98029_(int *);
  void hz98029(int flag) { hz98029_(&flag); }

  void hz98038_(int *);
  void hz98038(int flag) { hz98038_(&flag); }

  void hz98044_(int *);
  void hz98044(int flag) { hz98044_(&flag); }

  void hz98050_(int *);
  void hz98050(int flag) { hz98050_(&flag); }

  void hz98076_(int *);
  void hz98076(int flag) { hz98076_(&flag); }

  void hz98085_(int *);
  void hz98085(int flag) { hz98085_(&flag); }

  void hz98085p_(int *);
  void hz98085p(int flag) { hz98085p_(&flag); }

  void hz98087_(int *);
  void hz98087(int flag) { hz98087_(&flag); }

  void hz98092_(int *);
  void hz98092(int flag) { hz98092_(&flag); }

  void hz98121_(int *);
  void hz98121(int flag) { hz98121_(&flag); }

  void hz98143_(int *);
  void hz98143(int flag) { hz98143_(&flag); }

  void hz98162_(int *);
  void hz98162(int flag) { hz98162_(&flag); }

  void hz98169_(int *);
  void hz98169(int flag) { hz98169_(&flag); }

  void hz98204_(int *);
  void hz98204(int flag) { hz98204_(&flag); }

  void hz98205_(int *);
  void hz98205(int flag) { hz98205_(&flag); }

  void hz98210_(int *);
  void hz98210(int flag) { hz98210_(&flag); }

  void hz99057_(int *);
  void hz99057(int flag) { hz99057_(&flag); }

  void hz99091_(int *);
  void hz99091(int flag) { hz99091_(&flag); }

  void hz99094_(int *);
  void hz99094(int flag) { hz99094_(&flag); }

  void hz99101_(int *);
  void hz99101(int flag) { hz99101_(&flag); }

  void hz99126_(int *);
  void hz99126(int flag) { hz99126_(&flag); }

  void hz99193_(int *);
  void hz99193(int flag) { hz99193_(&flag); }

  void hzh0006017_(int *);
  void hzh0006017(int flag) { hzh0006017_(&flag); }

//   void hzh0108047_(int *);
//   void hzh0108047(int flag) { hzh0108047_(&flag); }

  void hzh0302034_(int *);
  void hzh0302034(int flag) { hzh0302034_(&flag); }

  void hzh0307071_(int *);
  void hzh0307071(int flag) { hzh0307071_(&flag); }

  void hzh0312057_(int *);
  void hzh0312057(int flag) { hzh0312057_(&flag); }

  void hzh0401010_(int *);
  void hzh0401010(int flag) { hzh0401010_(&flag); }

  void hzh0404033_(int *);
  void hzh0404033(int flag) { hzh0404033_(&flag); }

  void hzh0407018_(int *);
  void hzh0407018(int flag) { hzh0407018_(&flag); }

  void hzh0408149_(int *);
  void hzh0408149(int flag) { hzh0408149_(&flag); }

  void hzh0507089_(int *);
  void hzh0507089(int flag) { hzh0507089_(&flag); }

  void hzh0508055_(int *);
  void hzh0508055(int flag) { hzh0508055_(&flag); }

  void hzh0512014_(int *);
  void hzh0512014(int flag) { hzh0512014_(&flag); }

  void hzh0603014_(int *);
  void hzh0603014(int flag) { hzh0603014_(&flag); }

  void hzh0608042_(int *);
  void hzh0608042(int flag) { hzh0608042_(&flag); }

  void hzh9505001_(int *);
  void hzh9505001(int flag) { hzh9505001_(&flag); }

  void hzh9810020_(int *);
  void hzh9810020(int flag) { hzh9810020_(&flag); }

  void hzi02849_(int *);
  void hzi02849(int flag) { hzi02849_(&flag); }

  void hzth001_(int *);
  void hzth001(int flag) { hzth001_(&flag); }

  void hzth002_(int *);
  void hzth002(int flag) { hzth002_(&flag); }

  void hzth003_(int *);
  void hzth003(int flag) { hzth003_(&flag); }

}
#endif
