#!/bin/sh

# download and unpack the source files
# if headers are missing on debian, try installing apt-file
# and searching with 'apt-file search <filename>'

if ! test -f index.html; then

  wget http://wwwasd.web.cern.ch/wwwasd/cernlib/download/2005_source/tar/

  for i in $(grep -oe'"src_[^>]*.gz"' index.html | cut -d'"' -f2); do
    wget http://wwwasd.web.cern.ch/wwwasd/cernlib/download/2005_source/tar/$i;
  done

  wget http://www-zeuthen.desy.de/linear_collider/cernlib/new/cernlib.2005.corr.2009.06.13.tgz

  list=`ls src_*.gz`

  for ffile in $list
  do
    gunzip -c $ffile | tar xf -
  done

  tar -xzf cernlib.2005.corr.2009.06.13.tgz

  # -fPIC is essential for dynamic libs
  sed -e's/\(.define.*CcCmd\s*gcc\)/\1 -fPIC/g
s/\(.define.*FortranCmd\s*gfortran\)/\1 -fPIC -fno-automatic/g
s/\(.define.*FortranCmd\s*g77\)/\1 -fPIC -fno-automatic/g' -i 2005/src/config/linux.cf
  sed -e's/\(.define.*CcCmd\s*gcc\)/\1 -fPIC/g
s/\(.define.*FortranCmd\s*gfortran\)/\1 -fPIC -fno-automatic/g
s/\(.define.*FortranCmd\s*g77\)/\1 -fPIC -fno-automatic/g' -i 2005/src/config/linux-lp64.cf

fi

# Establish the environment variables for the build procedures
# Depending on the system, other directories may need to be added to the PATH
# e.g. for the build tools and alternative compilers.

CERN_LEVEL=`gunzip -c src_Imakefile.tar.gz | tar tf - | awk -F/ '{print $1}'`

CERN=`pwd`
CERN_ROOT=$CERN/$CERN_LEVEL
CVSCOSRC=$CERN/$CERN_LEVEL/src
PATH=$CERN_ROOT/bin:$PATH

export CERN
export CERN_LEVEL
export CERN_ROOT 
export CVSCOSRC
export PATH

# Create the build directory structure

cd $CERN_ROOT
mkdir -p build bin lib build/log

# Create the top level Makefile with imake

cd $CERN_ROOT/build
$CVSCOSRC/config/imake_boot

# Install kuipc and the scripts (cernlib, paw and gxint) in $CERN_ROOT/bin

gmake bin/kuipc
gmake scripts/Makefile
cd scripts
gmake install.bin

# Install the libraries

cd $CERN_ROOT/build
gmake

cd $CERN_ROOT/lib

# build shared libraries

for i in *.a; do
  rm -rf xxx; mkdir xxx; cd xxx;
  cp ../$i .; ar -x $i;
  NN=$(echo $i | sed -e's/[.]a/.so/g');
  echo creating $NN;
  ld -shared *.o -soname $NN.1 -o $NN.1.0;
  mv $NN.1.0 ../;
  cd ..;
  /sbin/ldconfig -l $NN.1.0
  if test -e $NN.1; then ln -sf $NN.1 $NN; fi
done

