@node Beam Parameters
@section Beam Parameters

The setup of the colliding beams is covered by the @file{(beam)}
section of the steering file or the beam data file @file{Beam.dat},
respectively, see @ref{Input structure}. The @emph{mandatory settings} to be made are

@itemize @bullet
@item The initial beam particles specified through 
@option{BEAM_1} and @option{BEAM_2}, given by their PDG 
particle number. For (anti)protons and (positrons) electrons, 
for example, these are given by (-)2212 or (-)11, respectively. 
The code for photons is 22. 
@item The energies of both incoming beams, defined through 
@option{BEAM_ENERGY_1} and @option{BEAM_ENERGY_2}, 
given in units of GeV.
@end itemize

A List of available Beam spectra is given in section
@ref{Beam Spectra}.

@menu
* Beam Spectra::  List of available beam spectra
@end menu

The following parameters are used to steer the beam setup.

@menu
* BEAM_1::            PDG ID of the first beam particle.
* BEAM_2::            PDG ID of the second beam particle.
* BEAM_ENERGY_1::     Energy of the first beam particle.
* BEAM_ENERGY_2::     Energy of the second beam particle.
* BEAM_SPECTRUM_1::   The Beamstrahlung spectrum for the first beam. 
* BEAM_SPECTRUM_2::   The Beamstrahlung spectrum for the second beam. 
* SPECTRUM_FILE_1::   Spectrum file name for the first beam.
* SPECTRUM_FILE_2::   Spectrum file name for the second beam.
* BEAM_SMIN::         Minimum fraction of cms energy after Beamstrahlung.
* BEAM_SMAX::         Maximum fraction of cms energy after Beamstrahlung.
* K_PERP_MEAN_1::     Mean primordial transverse momentum of first beam.
* K_PERP_MEAN_2::     Mean primordial transverse momentum of second beam.
* K_PERP_SIGMA_1::    Width of primordial transverse momentum distribution of first beam.
* K_PERP_SIGMA_2::    Width of primordial transverse momentum distribution of second beam.
@end menu


@node Beam Spectra
@subsection Beam Spectra
Possible values are
@table @option
@item Monochromatic
The beam energy is unaltered and the beam particles remain unchanged. 
That is the default and corresponds to ordinary hadron-hadron or 
lepton-lepton collisions.
@item Laser_Backscattering
This can be used to describe the backscattering of a laser beam
off initial leptons. The energy distribution of the emerging 
photon beams is modelled by the CompAZ parametrization, see
@mycite{Zarnecki2002qr}
Note that this parametrization is valid only for the proposed 
TESLA photon collider, as various assumptions about the laser 
parameters and the initial lepton beam energy have been made.
@item Simple_Compton
This corresponds to a simple light backscattering 
off the initial lepton beam and produces initial-state 
photons with a corresponding energy spectrum.
@item EPA
This enables the equivalent photon approximation for
colliding protons. The resulting beam particles are photons that 
follow a dipole form factor parametrization, see @mycite{Budnev1974de}
@item Spectrum_Reader
A user defined spectrum is used to describe the energy spectrum
of the assumed new beam particles. The name of the corresponding
spectrum file needs to be given through the keywords
@ref{SPECTRUM_FILE_1} and @ref{SPECTRUM_FILE_2}.
@end table


@node BEAM_1
@subsection BEAM_1
@cindex BEAM_1
This parameter specifies the PDG ID of the first (left) 
beam particle before eventual Beamstrahlung.


@node BEAM_2
@subsection BEAM_2
@cindex BEAM_2
This parameter specifies the PDG ID of the second (right) 
beam particle before eventual Beamstrahlung.


@node BEAM_ENERGY_1
@subsection BEAM_ENERGY_1
@cindex BEAM_ENERGY_1
This parameter specifies the energy of the first (left) 
beam particle in GeV.


@node BEAM_ENERGY_2
@subsection BEAM_ENERGY_2
@cindex BEAM_ENERGY_2
This parameter specifies the energy of the second (right) 
beam particle in GeV.

@node BEAM_SPECTRUM_1
@subsection BEAM_SPECTRUM_1
@cindex BEAM_SPECTRUM_1
This parameter specifies the Beamstrahlung spectrum for the first beam,
see @ref{Beam Spectra}.

@node BEAM_SPECTRUM_2
@subsection BEAM_SPECTRUM_2
@cindex BEAM_SPECTRUM_2
This parameter specifies the Beamstrahlung spectrum for the second beam,
see @ref{Beam Spectra}.

@node SPECTRUM_FILE_1
@subsection SPECTRUM_FILE_1
@cindex SPECTRUM_FILE_1
This parameter specifies the spectrum file for the first beam,
see @ref{Beam Spectra}.

@node SPECTRUM_FILE_2
@subsection SPECTRUM_FILE_2
@cindex SPECTRUM_FILE_2
This parameter specifies the spectrum file for the first beam,
see @ref{Beam Spectra}.

@node BEAM_SMIN
@subsection BEAM_SMIN
@cindex BEAM_SMIN
This parameter specifies the minimum fraction of cms energy
squared after Beamstrahlung. The reference value is the total centre
of mass energy squared of the collision, @emph{not} the 
centre of mass energy after eventual Beamstrahlung.
@*
The parameter can be specified using the internal interpreter, see
@ref{Interpreter}, e.g. as @samp{BEAM_SMIN sqr(20/E_CMS)}.

@node BEAM_SMAX
@subsection BEAM_SMAX
@cindex BEAM_SMAX
This parameter specifies the minimum fraction of cms energy
squared after Beamstrahlung. The reference value is the total centre
of mass energy squared of the collision, @emph{not} the 
centre of mass energy after eventual Beamstrahlung.
@*
The parameter can be specified using the internal interpreter, see
@ref{Interpreter}, e.g. as @samp{BEAM_SMIN sqr(0.99)}.

@node K_PERP_MEAN_1
@subsection K_PERP_MEAN_1
@cindex K_PERP_MEAN_1
This parameter specifies the mean intrinsic transverse
momentum for the first (left) beam in case of hadronic 
beams, such as protons.
@*
The default value for protons is 0.33 GeV.

@node K_PERP_MEAN_2
@subsection K_PERP_MEAN_2
@cindex K_PERP_MEAN_2
This parameter specifies the mean intrinsic transverse
momentum for the second (right) beam in case of hadronic 
beams, such as protons.
@*
The default value for protons is 0.33 GeV.

@node K_PERP_SIGMA_1
@subsection K_PERP_SIGMA_1
@cindex K_PERP_SIGMA_1
This parameter specifies the width of the Gaussian distribution
of intrinsic transverse momentum for the first (left) beam in 
case of hadronic beams, such as protons.
@*
The default value for protons is 0.8 GeV.

@node K_PERP_SIGMA_2
@subsection K_PERP_SIGMA_2
@cindex K_PERP_SIGMA_2
This parameter specifies the width of the Gaussian distribution
of intrinsic transverse momentum for the first (left) beam in 
case of hadronic beams, such as protons.
@*
The default value for protons is 0.8 GeV.

