@node Command line
@chapter Command line options 

The available command line options for Sherpa.

@table @option

@item --run-data, -f <file>
Read settings from input file @samp{<file>}.

@item --path, -p <path>
Read input file from path @samp{<path>}.

@item --sherpa-lib-path, -L <path>
Set Sherpa library path to @samp{<path>},
see @ref{SHERPA_CPP_PATH}.

@item --events, -e <N_events>
Set number of events to generate @samp{<N_events>},
see @ref{EVENTS}.

@item --event-type, -t <event_type>
Set the event type to @samp{<event_type>},
see @ref{EVENT_TYPE}.

@item --result-directory, -r <path>
Set the result directory to @samp{<path>},
see @ref{RESULT_DIRECTORY}.

@item --random-seed, -R <seed>
Set the seed of the random number generator to @samp{<seed>},
see @ref{RANDOM_SEED}.

@item --me-generators, -m <generators>
Set the matrix element generator list to @samp{<generators>},
see @ref{ME_GENERATORS}. If you specify more than one generator, use the YAML
sequence syntax, e.g. @samp{-m '[Amegic, Comix]'}.

@item --mi-handler, -M <handler>
Set multiple interaction handler to @samp{<handler>}, see @ref{MI_HANDLER}.

@item --event-generation-mode, -w <mode>
Set the event generation mode to @samp{<mode>},
see @ref{EVENT_GENERATION_MODE}.

@item --shower-generator, -s <generator>
Set the parton shower generator to @samp{<generator>},
see @ref{SHOWER_GENERATOR}.

@item --fragmentation, -F <module>
Set the fragmentation module to @samp{<module>},
see @ref{Fragmentation}.

@item --decay, -D <module>
Set the hadron decay module to @samp{<module>},
see @ref{Hadron decays}.

@item --analysis, -a <analyses>
Set the analysis handler list to @samp{<analyses>},
see @ref{ANALYSIS}.
If you specify more than one analysis handler, use the YAML sequence syntax,
e.g. @samp{-a '[Rivet, Internal]'}.

@item --analysis-output, -A <path>
Set the analysis output path to @samp{<path>},
see @ref{ANALYSIS_OUTPUT}.

@item --output, -O <level>
Set general output level @samp{<level>}, see @ref{OUTPUT}.

@item --event-output, -o <level>
Set output level for event generation @samp{<level>}, see @ref{OUTPUT}.

@item --log-file, -l <logfile>
Set log file name @samp{<logfile>}, see @ref{LOG_FILE}.

@item --disable-result-directory-generation, -g
Do not create result directory, see @ref{RESULT_DIRECTORY}.

@item --disable-batch-mode, -b
Switch to non-batch mode, see @ref{BATCH_MODE}.

@item --print-version-info, -V
Print extended version information at startup.

@item --version, -v
Print versioning information.

@item --help, -h
Print a help message.

@item 'PARAMETER: Value'
Set the value of a parameter, see @ref{Parameters}.

@item 'Tags: @{TAG: Value@}'
Set the value of a tag, see @ref{Tags}.

@end table

