@node Cross section
@chapter Cross section

To determine the total cross section, in particular 
in the context of running CKKW merging with Sherpa, 
the internal analysis package provided within Sherpa
can be employed. A file @file{Analysis.dat} needs 
to be created containing the lines
@verbatim
BEGIN_ANALYSIS {
  LEVEL Hadron;
  PATH_PIECE Norm/;
  Statistics FinalState;
} END_ANALYSIS;
@end verbatim
and added to the directory where @file{Run.dat} resides.
Doing SHERPA internal analyses has to be enabled using 
@option{ANALYSIS=1}, either in the @file{(run)} section
of @file{Run.dat} or on the command line. After program
termination, a file @file{Statistics_Observable_FinalState}
can be found in the @file{Norm} subdirectory of
the analysis-result path that was specified for the run 
by @option{ANALYSIS OUTPUT}. As an example a file for
pp->e+e- is listed below:
@verbatim
# Process Name      # evts       <w>   <sigma>   <Delta>
2_2__b__bb__e-__e+       1   0.36933  0.399068   0.92548
2_2__c__cb__e-__e+       2  0.566878  0.595396  0.952103
2_2__d__db__e-__e+     271    58.455   62.8626  0.929885
2_2__s__sb__e-__e+      28   4.78567   5.14493  0.930172
2_2__u__ub__e-__e+     443   97.4499   104.727  0.930514
...

# Total XS : 177.015 +- ( 3.64851 = 2.06113 % )

@end verbatim
The first column contains the process name, the second the
number of generated events for that process. The third column
gives the mean weight for the process, which is composed
of matrix-element and Sudakov weight. The respective averages
of the latter two are given in the last two columns. Finally,
the total cross section is listed at the end of the file. 
Note that the Monte Carlo error quoted for the total cross
section is determined during event generation. Therefore,
it differs substantially from the error quoted during the 
integration step.
