@node Customization
@chapter Customization
@cindex SHERPA_LDADD

Customizing Sherpa according to your needs.

Sherpa can be easily extended with certain user defined tools.
To this extent, a corresponding class must be written,
equipped with a corresponding getter function and compiled into
an external library which can be linked to Sherpa at runtime. 
To this end the switch @code{SHERPA_LDADD} has to be given the 
name of the library to be loaded, ie.

@verbatim
  SHERPA_LDADD <libname>
@end verbatim

to load @code{lib<libname>.so}. 
Several specific examples are listed in the following sections.

@menu
* External RNG::     How to add an external random number generator.
* External PDF::     How to add an external PDF.
* Exotic physics::   How to introduce your own models to Sherpa. Example: Z-prime.
* External one-loop ME:: How to interface external one-loop codes.
* My own interface:: How to make Sherpa send output to your framework.
* API::              How to make Sherpa talk to your Python script.
@end menu

@include RNG.texi
@include PDF.texi
@include NewModel.texi
@include OLE.texi
@include MyInterface.texi
@include API.texi
