@node EGamma
@section EGamma

@example
@smallformat
@verbatiminclude Examples/EGamma/Run.dat
@end smallformat
@end example


Things to notice:
@itemize @bullet
@item the incoming beams are both electrons. Accordingly, 
in the @code{(beam)} section of the data card, the beams 
are set as electrons by @code{BEAM_@{1,2@}=11}.

@item the photon is produced through laser backscattering
off one of the incoming electrons. 
@code{BEAM_SPECTRUM_1=Laser_Backscattering} and
@code{BEAM_SPECTRUM_2=Monochromatic} have been specified.

@end itemize

