@node Examples
@chapter Examples

Some example set-ups are included in Sherpa, in the 
@code{<prefix>/share/SHERPA-MC/Examples/} directory. These may be useful to 
new users to practice with, or as templates for creating your 
own Sherpa run-cards. In this section, we will look at some 
of the main features of these examples.

@menu
* VJets::
* Jets::
* HJets::
* FONLO::
@end menu


@node VJets
@section Vector boson production in association with jets

@menu
* LHC_WJets::
* LHC_ZJets::
@end menu

@include LHC_WJets.texi
@include LHC_ZJets.texi


@node Jets
@section Jet production

@menu
* LHC_Jets::
* HERA_DIS::
* LEP_Jets::
@end menu

@include LHC_Jets.texi

@node HERA_DIS
@subsection Jet production in DIS at HERA

@node LEP_Jets
@subsection Jet production at LEP I


@node HJets
@section Higgs boson production in association with jets

@menu
* LHC_HJets::
@end menu

@include LHC_HJets.texi

@node FONLO
@section Fixed-order next-to-leading order calculations

@menu
* NLO_W::                    W production at the LHC
* LHC_WJet_LHOLE::           W+jet production at the LHC using the BLHA interface
@end menu

@node NLO_W
@subsection NLO_W

@node LHC_WJet_LHOLE
@subsection LHC_WJet_LHOLE

