@node Examples
@chapter Examples

Some example set-ups are included in Sherpa, in the 
@code{<prefix>/share/SHERPA-MC/Examples/} directory. These may be useful to 
new users to practice with, or as templates for creating your 
own Sherpa run-cards. In this section, we will look at some 
of the main features of these examples.

@menu
* LHC_ZJets::                 
* Tevatron_ZJets::            
* Tevatron_WJets::            
* Tevatron_QCD::              
* LEP91::                     
* LHC_TopPair::               
* Tevatron_TopPair::          
* Tevatron_UE::               
* Tevatron_DiBoson::          
* EGamma::                    
* PEPII_BaBar::               
* LHC_4thGen::                
* LHC_AGC::                   
* LHC_ADD::
* NLO_W::
@end menu

@include LHC_ZJets.texi
@include Tevatron_ZJets.texi
@include Tevatron_WJets.texi
@include Tevatron_QCD.texi
@include LEP91.texi
@include LHC_TopPair.texi
@include Tevatron_TopPair.texi
@include Tevatron_UE.texi
@include Tevatron_DiBoson.texi
@include EGamma.texi
@include PEPII_BaBar.texi
@include LHC_4thGen.texi
@include LHC_AGC.texi
@include LHC_ADD.texi
@include W_NLO.texi


