@node Fragmentation
@section Fragmentation

The hadronization setup is covered by the `(fragmentation)' section of
the steering file or the fragmentation data file `Fragmentation.dat', respectively.

@menu
* FRAGMENTATION::           The fragmentation module.
@end menu


@node FRAGMENTATION
@subsection FRAGMENTATION
@cindex FRAGMENTATION
The fragmentation module to be employed during event generation.
This parameter can also be set on the command line using option @option{-F},
see @ref{Command line}. The default is @option{Ahadic}.

