@node Integration
@section Integration

The integration setup is covered by the `(integration)' section of
the steering file or the integration data file `Integration.dat',
respectively.

The following parameters are used to steer the integration.

@menu
* ERROR::                The realtice integration error target
* INTEGRATOR::           The integrator type
* VEGAS::                Whether to enable Vegas
* FINISH_OPTIMIZATION::  Whether to fully optimise the Vegas grid
* PSI_NMAX::             Maximum number of points per process
@end menu


@node ERROR
@subsection ERROR
@cindex ERROR
Specifies the relative integration error target.


@node INTEGRATOR
@subsection INTEGRATOR
@cindex INTEGRATOR
Specifies the integrator. The possible integrator types
depend on the matrix element generator. Users should
rely on the default value and otherwise seek the help 
of the authors, see @ref{Authors}.


@node VEGAS
@subsection VEGAS
@cindex VEGAS
Specifies whether or not to employ Vegas for adaptive integration.
The two possible values are @option{On} and @option{Off}, the
default being @option{On}.


@node FINISH_OPTIMIZATION
@subsection FINISH_OPTIMIZATION
@cindex FINISH_OPTIMIZATION
Specifies whether the full Vegas optimization is to be carried out.
The two possible options are @option{On} and @option{Off}, the
default being @option{On}.

@node PSI_NMAX
@subsection PSI_NMAX
@cindex PSI_NMAX
The maximum number of points before cuts to be generated during integration.
This parameter acts on a process-by-process basis.
