@node ISR Parameters
@section ISR Parameters
@cindex BUNCH_1
@cindex BUNCH_2
@cindex ISR_1
@cindex ISR_2
@cindex ISR_SMIN
@cindex ISR_SMAX
@cindex ISR_E_ORDER
@cindex ISR_E_SCHEME
@cindex PDF_LIBRARY
@cindex PDF_SET
@cindex PDF_SET_VERSION
@cindex PDF_GRID_PATH
@cindex SHOW_PDF_SETS

The following parameters are used to steer the setup of beam substructure and
initial state radiation. They may be set in the
@code{(isr)} section of the run-card, see @ref{Input structure}.

@table @code
@item BUNCH_1/BUNCH_2
Specify the PDG ID of the first
(left) and second (right) bunch particle, i.e. the particle after eventual 
Beamstrahlung specified through the beam parameters, see @ref{Beam Parameters}.
Per default these are taken to be identical to the parameters 
@code{BEAM_1}/@code{BEAM_2}, assuming the default beam spectrum is
Monochromatic. In case the Simple Compton or Laser Backscattering spectra are
enabled the bunch particles would have to be set to 22, the PDG code of the
photon.

@item ISR_1/ISR_2
Specifies whether ISR is enabled for the
first/second bunch particle.
Possible values are @option{On} and @option{Off}.
@*
For bunch particles with hadronic substructure, i.e.
hadrons and photons, this amounts to employing a PDF 
to extract partons.
@*
@table @var
@item Proton bunches
For incoming protons, ISR must be enabled, which is ensured by default.
@item  Photons
For colliding photons, this parameter defines if the resolved or unresolved
component of the cross section is to be considered.
@item Leptons
For leptons this switch steers the inclusion of a structure function,
corresponding to the emission of undetected photons `before' the actual
lepton-lepton interaction.
@end table

@item ISR_SMIN/ISR_SMAX
This parameter specifies the minimum fraction of cms energy
squared after ISR. The reference value is the total centre
of mass energy squared of the collision, @emph{not} the 
centre of mass energy after eventual Beamstrahlung.
@*
The parameter can be specified using the internal interpreter,
see @ref{Interpreter}, e.g. as @samp{ISR_SMIN=sqr(20/E_CMS)}.
@end table

Sherpa provides access to a variety of structure functions.
They can be configured with the following parameters.

@table @code
@item PDF_LIBRARY
Switches between different interfaces to PDFs. The following options are
distributed with Sherpa:
@table @code
@item LHAPDFSherpa
Use PDF's from LHAPDF @mycite{Whalley2005nh}. This is the default (and only
available then) if Sherpa has been compiled with support for LHAPDF, see
@ref{Installation}.
@item CTEQ6Sherpa
Built-in library for some PDF sets from the CTEQ collaboration, cf.
@mycite{Pumplin2002vw}. This is the
default, if Sherpa has not been compiled with LHAPDF support.
@item MRST99Sherpa
Built-in library for some PDF sets from the MRST group, cf. @mycite{Martin1999ww}.
@item MRST01LOSherpa
Built-in library for another PDF set from the MRST group, cf. @mycite{Martin2001es}.
@item MRST04QEDSherpa
Built-in library for photon PDF sets from the MRST group, cf. @mycite{Martin2004dh}.
@item GRVSherpa
Built-in library for the GRV photon PDF @mycite{Gluck1991jc}, @mycite{Gluck1991ee}
@item PDFESherpa
Built-in library for the electron structure function.
The perturbative order of the fine structure constant can be set using the
parameter @anchor{ISR_E_ORDER} @code{ISR_E_ORDER} (default: 1). The
switch @anchor{ISR_E_SCHEME} @code{ISR_E_SCHEME} allows
to set the scheme of respecting non-leading terms. Possible options are 0
("mixed choice"), 1 ("eta choice"), or 2 ("beta choice", default).
@end table
@*
Furthermore it is simple to built an external interface to an arbitrary PDF
and load that dynamically in the Sherpa run. See @ref{External PDF} for
instructions.
@item PDF_SET
Specifies the PDF set for hadronic bunch particles. All sets available in the
chosen @code{PDF_LIBRARY} can be figured by running Sherpa with the parameter
@code{SHOW_PDF_SETS=1}, e.g.:
@verbatim
  Sherpa PDF_LIBRARY=CTEQ6Sherpa SHOW_PDF_SETS=1
@end verbatim  
@item PDF_SET_VERSION
This parameter allows to eventually select a specific version (member)
within the chosen PDF set.
@item PDF_GRID_PATH
For the internal PDF sets this parameter may be specified to select the
directory where the PDF grid files are located.
@end table
