@node LHC_WJets
@subsection W+jets production at the LHC

@menu
* LHC_W1jet_MCatNLO::
* LHC_WJets_LOmerging::
* LHC_WJets_NLOmerging::
@end menu

To change any of the following examples to production at the Tevatron 
simply change the beam settings to
@verbatim
  BEAM_1  2212; BEAM_ENERGY_1 980;
  BEAM_2 -2212; BEAM_ENERGY_2 980;
@end verbatim


@node LHC_W1jet_MCatNLO
@subsubsection MC@@NLO setup for pp->W+jet+X

@example
@smallformat
@verbatiminclude Examples/V_plus_Jets/LHC_W1jet_MCatNLO/Run.dat
@end smallformat
@end example

@node LHC_WJets_LOmerging
@subsubsection MEPS and MENLOPS setup for pp->W+jets

@example
@smallformat
@verbatiminclude Examples/V_plus_Jets/LHC_WJets/Run.dat
@end smallformat
@end example

@node LHC_WJets_NLOmerging
@subsubsection MEPS@@NLO setup for pp->W+jets

@example
@smallformat
@verbatiminclude Examples/V_plus_Jets/LHC_WJets/Run.NLO.dat
@end smallformat
@end example


