To change any of the following LHC examples to production at different
collider energies or beam types, e.g. proton anti-proton at the Tevatron,
simply change the beam settings accordingly:
@verbatim
  BEAMS: [2212, -2212]
  BEAM_ENERGIES: 980
@end verbatim

@node LHC_WJets
@subsection W+jets production

This is an example setup for inclusive W production at hadron colliders. 
The inclusive process is calculated at next-to-leading order accuracy matched 
to the parton shower using the MC@@NLO prescription detailed in 
@mycite{Hoeche2011fd}. The next few higher jet multiplicities, calculated at 
next-to-leading order as well, are merged into the inclusive sample using 
the MEPS@@NLO method -- an extension of the CKKW method to NLO -- as described 
in @mycite{Hoeche2012yf} and @mycite{Gehrmann2012yg}. Finally, even higher 
multiplicities, calculated at leading order, are merged on top of that.
A few more things to note are detailed below the example. 

@example
@smallformat
@verbatiminclude Examples/V_plus_Jets/LHC_WJets/Sherpa.yaml
@end smallformat
@end example

Things to notice:
@itemize
@item The multiplicities calculated at NLO accuracy are given by the
@code{2->2-4} key below the @code{# set up MC@@NLO ...} comment.
The example can be converted into a simple MENLOPS setup by using @code{2->2}
instead, or into
an MEPS setup by using some non-existent multiplicity, e.g. @code{2->0}.
Thus one can study the effect of incorporating higher-order
matrix elements.
@item The number of additional LO jets can be varied
through changing the integer within the curly braces in the @code{Process}
definition, which gives the maximum number of additional partons in the
matrix elements.
@item @code{OpenLoops} is used here as the provider of the one-loop
matrix elements for the respective multiplicities.
@item Tau leptons are set massive in order to exclude them from the massless 
lepton container (@code{90}).
@item As both Comix and Amegic are specified as matrix element generators 
to be used, Amegic has to be specified to be used for all MC@@NLO 
multiplicities using @code{ME_Generator: Amegic}. Additionally, we
specify @code{RS_ME_Generator: Comix} such that the subtracted
real-emission bit of the NLO matrix elements is calculated more efficiently
with Comix instead of Amegic.
@end itemize

The jet criterion used to define the matrix element multiplicity in the
context of multijet merging can be supplied by the user. As an example
the source code file @code{./Examples/V_plus_Jets/LHC_WJets/My_JetCriterion.C}
provides such an alternative jet criterion. It can be compiled using
@code{SCons} via executing @code{scons} in that directory (edit the
@code{SConstruct} file accordingly). The newly created library is linked
at run time using the @code{SHERPA_LDADD} flag.
The new jet criterion is then evoked by @code{JET_CRITERION}.

