@node LHC_Wbb
@subsection W+bb production

@example
@smallformat
@verbatiminclude Examples/V_plus_Bs/LHC_Wbb/Run.dat
@end smallformat
@end example

Things to notice:
@itemize
@item The matrix elements are interfaced from @mycite{FebresCordero2006sj}.
  The shared library necessary for running this setup is built using
  @uref{http://www.scons.org/,,scons}.
@item The W-boson is stable in the hard matrix elements.
  It is decayed using the internal decay module, indicated by
  the settings @option{HARD_DECAYS 1} and @option{STABLE[24] 0}.
@item @uref{http://www.fastjet.fr/,,FastJet} is used to regularize the hard cross section. 
  Note that Sherpa must be configured with option @option{--enable-fastjet}, see
  @ref{Fastjet selector}. We require two b-jets, indicated by the @option{2} 
  at the end of the @option{FastjetFinder} options.
@item Four-flavour PDF's are used to comply with the calculational setup.
@end itemize
 

@node LHC_Zbb
@subsection Zbb production

@example
@smallformat
@verbatiminclude Examples/V_plus_Bs/LHC_Zbb/Run.dat
@end smallformat
@end example

Things to notice:
@itemize
@item The matrix elements are interfaced via the
  Binoth Les Houches interface proposal @mycite{Binoth2010xt},
  @mycite{Alioli2013nda}, @ref{External one-loop ME}.
@item The Z-boson is stable in the hard matrix elements.
  It is decayed using the internal decay module, indicated by
  the settings @option{HARD_DECAYS 1} and @option{STABLE[24] 0}.
@item @uref{http://www.fastjet.fr/,,FastJet} is used to regularize the hard cross section.
  Note that Sherpa must be configured with option @option{--enable-fastjet}, see
  @ref{Fastjet selector}. We require two b-jets, indicated by the @option{2}
  at the end of the @option{FastjetFinder} options.
@item Four-flavour PDF's are used to comply with the calculational setup.
@end itemize


@node LHC_Fusing
@subsection Zbb Fusing
The fusing algorithm as introduced in @mycite{Hoche2019ncc} aims for a consistent, combined 
prediction of a 4FS simulation and a merged 5FS prediction.
The new simulation is hereby formed as sum of two components. 
First, the direct component is given by the 4FS calculation.
It is reformulated as if it would be part of a merged simulation and while
doing so, the Sudakov rejection by the parton shower will actually remove events.
The fragmentation component then is given by the original, merged 5FS simulation.
All configurations which are already described by the direct component are removed by an event filter.

Since the event filter operates on combined evolution histories, treating 
actual emissions from the parton shower and clustered emissions from matrix elements on the same footing, 
it must be ensured that the same cluster options are used everywhere.

The following run card parameters summarize all settings which where used for @mycite{Hoche2019ncc}.

@subsubsection The direct component

@example
@smallformat
@verbatiminclude Examples/V_plus_Bs/LHC_Fusing/Run.direct
@end smallformat
@end example

Things to notice:
@itemize
@item The PDF and the strong coupling constant are evaluated in the 5FS. 
This is needed for consistency and to allow cluster configurations with initial-state bottom quarks.
The resulting mismatch is corrected by counter-terms, implemented as user hook.
If two strong couplings are involved at Born level, @option{FUSING_DIRECT_FACTOR} must be set to one.
If there are four such couplings, as in case of ttbb, it must be two.
@item From a physical point of view, no merging cut is needed for massive bottom quarks. 
For technical reasons, it nevertheless must be set to an unreachable value such as @option{CKKW 100000.0}.

@end itemize


@subsubsection The fragmentation component

@example
@smallformat
@verbatiminclude Examples/V_plus_Bs/LHC_Fusing/Run.frag
@end smallformat
@end example

Things to notice:
@itemize
@item The event filter can either be performed directly (default), or the veto information can be stored in HepMC. 
The latter requires @option{HEPMC_USE_NAMED_WEIGHTS=1} and  @option{FUSING_FRAGMENTATION_STORE_AS_WEIGHT=1}. 
The correspending weight is set to zero in case there is a fusing-induced event veto but remains unchanged if not.
@end itemize

