@node LHC_Jets
@subsection Jet production at Hadron Colliders

@menu
* LHC_2jets_MCatNLO::
* LHC_Jets_MEPS::
* Tevatron_Jets_MEPS::
@end menu

@node LHC_2jets_MCatNLO
@subsubsection MC@@NLO setup for dijet and inclusive jet production at the LHC

@example
@smallformat
@verbatiminclude Examples/Jets_at_HadronColliders/LHC_2jets_MCatNLO/Run.dat
@end smallformat
@end example


@node LHC_Jets_MEPS
@subsubsection MEPS setup for jet production at LHC

@example
@smallformat
@verbatiminclude Examples/Jets_at_HadronColliders/LHC_Jets_MEPS/Run.dat
@end smallformat
@end example


@node Tevatron_Jets_MEPS
@subsubsection MEPS setup for jet production at Tevatron

This example generates QCD events at the Tevatron,
with 2, 3 or 4 final state partons in the matrix
element.

@example
@smallformat
@verbatiminclude Examples/Jets_at_HadronColliders/Tevatron_Jets_MEPS/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item
@code{Order_EW} is set to @option{0}. This
ensures that all final state jets are produced via 
the strong interaction.

@item
an @code{NJetFinder} selector is used to 
set a resolution criterion for the two jets of the core process.
This is necessary because the `CKKW' tag does not apply any cuts to the core
process, but only to the extra-jet matrix elements, see @ref{Merging ME and PS}.
This cut is applied only to the 2->2 process using the @code{@{2@}}
specification, since the higher-order matrix elements should only be cut by
the ME+PS separation criterion.
@end itemize
