@node LHC_ZJets
@subsection LHC_ZJets

This example is for an LHC set-up, with a proton--proton collision at 
centre of mass energy 14TeV. The final state is an electron--positron 
pair and up to 4 partons from the matrix element.

@example
@smallformat
@comment @verbatiminclude Examples/V_plus_Jets/LHC_ZJets_MENLOPS/Run.dat
@end smallformat
@end example
 
Things to notice:
@itemize @bullet
@item the number of events generated is set in the @code{(run)} section.
If this parameter is not set, 100 events will be generated.

@item the beam particles are specified in the @code{(beam)} section, using 
PDG codes, see @ref{PDG codes}. The beam energy must also be specified in GeV.

@item the process is specified in the @code{(processes)} section, using PDG codes
again. @option{93} is a particle container for light quarks and gluons, see 
@ref{Particle containers}. The @option{4} in curly brackets after the final state 
@option{93} means that the matrix element will be generated with up to 4 extra partons
in the final state, see @ref{Curly brackets}.

@item the multi-jet merging parameter @ref{CKKW} is set
using an algebraic expression. For more information on
algrebraic expressions recognised by Sherpa, see 
@ref{Interpreter}. For more information on the CKKW 
parameter and the Sherpa method for merging matrix elements
and parton showers, see @ref{Merging ME and PS}.

@item the @ref{Integration_Error} is set separately for some of the final state 
multiplicities. The higher multiplicity cross sections are smaller, so
to get the same order of magnitude for the absolute error in the 
cross section integrations, the relative error can be higher. 

@item there is a selector cut on the invariant mass of the lepton pair. This cut 
shields the IR singularity as the invariant mass tends to zero, and
focuses on the area around the Z-peak, from 66Gev to 116GeV.

@item the matrix element signal generators have been chosen to be the Internal
hard coded ones in module EXTRA_XS, and Comix.

@item multiple interactions have been switched off. 
@end itemize
















