@node LHC_SingleTop
@section LHC_SingleTop

This set-up illustrates the possibility of removing a
resonant contribution from the signal process.

@example
@smallformat
@verbatiminclude Examples/LHC_SingleTop/Run.dat
@end smallformat
@end example

The process generated is the production of a single top quark in association 
with up to three light partons in the final state.
The top quark decays into a bottom quark and a W-boson. 
The resonant production of a top-antitop final state in the Wt-mode
is excluded by diagram removal.

Things to notice:
@itemize @bullet
@item the tag @code{No_Decay} is used to specify the resonances to be avoided, 
see @ref{No_Decay}. In this example, the contribution from s-channel antitop 
quark propagators is excluded.

@item the decaying particles have labels. In order to specify a decay, the 
decaying particle must be given an identifier, eg @option{6[a]}, @option{24[c]} etc. Each
identifier must be unique within any given process, and must be included 
when specifying the particle's production, and it's decay.

@item the particle containers for charged leptons (@option{90}), neutrinos 
(@option{91}), quarks (@option{94}) and massless partons (@option{93}) are
all used in this example. See @ref{Particle containers}.
@end itemize



