@node LHC_HWBF
@subsection H+jets production in weak boson fusion

This is an example setup for inclusive Higgs production through 
weak boson fusion at hadron colliders. The inclusive process is calculated 
at leading order accuracy merged with up to one additional jet using 
the ME+PS prescription detailed in @mycite{Hoeche2009rj}. This example
shows how to implement and use a custom core scale in Sherpa 
@ref{METS scale setting with multiparton core processes}.

@example
@smallformat
@verbatiminclude Examples/H_in_WBF/LHC_HJets_MEPS/Run.dat
@end smallformat
@end example

Things to notice:
@itemize
@item The core scale is defined in the file @code{WBF_Core_Scale.C}.
  The shared library necessary for running the setup is built using
  @uref{http://www.scons.org/,,scons}.
@item The Higgs boson is stable in the hard matrix elements.
  It is decayed using the internal decay module, indicated by
  the settings @option{HARD_DECAYS 1} and @option{STABLE[25] 0}.
@end itemize
 
