@node LHC_SUSY
@section LHC_SUSY

This example shows a beyond the Standard Model set-up, namely a
setup for the Minimal Supersymmetric Standard Model (MSSM). This is 
one of Sherpa's built-in BSM options, see @ref{Models available in Sherpa}. 
For more information on using your own BSM models with Sherpa, see 
@ref{Exotic physics}.

@example
@smallformat
@verbatiminclude Examples/LHC_SUSY/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item the model is chosen in the @code{(model)} section of
the run card, using the parameter @code{MODEL}, see
@ref{Model Parameters}. The default is the SM. 

@item the necessary SUSY Les Houches Accord input file containing all parameters
is set by @code{SLHA_INPUT}, see @ref{MSSM}.

@item the process is specified with up to one extra parton in the production 
subprocess, see @ref{Curly brackets}.

@item the multi-jet merging parameter @ref{CKKW} is set
using an algebraic expression, see @ref{Merging ME and PS}.

@item the tag @code{DecayOS} is used to specify the decays. See @ref{DecayOS}.

@item the matrix element generator AMEGIC++ is used
for this set-up, see @ref{Running Sherpa with AMEGIC++}.
@end itemize







