@node LHC_4thGen
@section LHC_4thGen

This example shows a beyond the Standard Model set-up. In 
this example, a 4th generation of particles is included, as 
well as the Standard Model particles. This is one of Sherpa's
built-in BSM options, see @ref{Models available in Sherpa}. 
For more information
on using your own BSM models with Sherpa, see 
@ref{Exotic physics}.

@example
@smallformat
@verbatiminclude Examples/LHC_4thGen/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item the matrix element generator AMEGIC++ is used
for this set-up. @ref{Running Sherpa with AMEGIC++} is decribed
below.

@item the model is chosen in the @code{(model)} section of
the run card, using the parameter @code{MODEL}, see
@ref{Model Parameters}. The default is the SM. 

@item for a full description of all parameters in any 
chosen model, use the tag @code{SHOW_MODEL_SYNTAX=1} 
on the command line when running Sherpa.

@item the properties of the 4th generation fermions, 
such as @code{MASS[<id>]} and @code{WIDTH[<id>]},
may be set in the runcard, or on the command line, 
in exactly the same way as the SM particle
properties. In the above example, only the fourth
generation lepton masses and widths have been set. The 
corresponding parameters of the fourth generation
quarks were left at their default values since they do 
not play a role in this process.

@item the 3x3 mixing matrices for quarks (CKM matrix)
and leptons (unit matrix) are supplemented with three
additional mixing angles and two additional phases
according to @mycite{Hou1987vd}. Note that in the
above example only small mixing of the 4th and the 3rd
generation of leptons is allowed. For all relevant
switches and their defaults see @ref{4thGen}. Again,
the corresponding parameters for the quark sector
were left at their default values since they do not 
play a role here.

@item the switch OUTPUT_MIXING is used to print the 4x4
mixing matrices for leptons and quarks on screen at the
beginning of each run, just before the particle content
of the model.

@item the analysis has been switched off, but
to use it, switch @ref{ANALYSIS} to @option{Internal}.

@item the analysis in this example uses Sherpa's
in-built analysis package. To use this Analysis 
package, when Sherpa is installed, the option
@kbd{--enable-analysis} must be include on the 
command line when Sherpa is configured, see 
@ref{ANALYSIS}. To display the Analysis
package syntax, run Sherpa with 
@code{SHOW_ANALYSIS_SYNTAX=1} on the command line.
@end itemize








