@set spires http://www-spires.dur.ac.uk/cgi-bin/spiface/hep/www?rawcmd=

@macro mybibmake{llink,lref}
@end macro

@macro mycite{ref}
@ifinfo
[@value{K\ref\}] in @ref{References}.
@set U\ref\ true
@end ifinfo
@ifnotinfo
@set U\ref\ true
[@ref{\ref\, @value{K\ref\}}].
@end ifnotinfo
@end macro

@macro mybibitem{ref,key,author,title,journal,vol,year,pages,eprint,slink}
@ifclear mybibout
@set K\ref\ \key\
@clear U\ref\
@end ifclear
@ifset U\ref\
@item
@ifinfo
@anchor{\ref\}[\key\] 
@end ifinfo
@ifnotinfo
@anchor{\ref\}[@uref{@value{spires}\slink\,\key\}] 
@end ifnotinfo
\author\, @emph{\title\}, \journal\ @b{\vol\}\year\\pages\ \eprint\.
@ifinfo
@sp 1
@end ifinfo
@ifnotinfo
@sp 2
@end ifnotinfo
@end ifset
@end macro

@macro mybibbegin{filename}
@include \filename\
@end macro

@macro mybibend{filename}
@node References
@chapter References
@itemize @asis
@set mybibout true
@include \filename\
@end itemize
@end macro
