@node ME2
@subsection Computing matrix elements for idividual phase space points
Sherpa's Python interface (see @ref{Python Interface}) can be used to
compute matrix elemtents for individual phase space points.  Access to a
designated class ``MEProcess'' is provided by interface to compute
matrix elements as illustrated in the example script.

Please note that the process in the script must be compatible with the
one specified in the run card in the working directory.  This also
applies to the initial state particle momenta as well as the masses of
all external particles.

If AMEGIC++ is used as the matrix element generator, executing the
script will result in AMEGIC++ writing out libraries and exiting.
After compiling the libraries using @code{./makelibs}, the script must
be executed again in order to obtain the matrix element. On some
systems, this might result in a termination with errors of the form
@verbatim
Library_Loader::LoadLibrary(): ./Process/lib/libProc_P2_2_2_6_24_16_5_0.so: undefined symbol: _ZN6AMEGIC10Basic_Func1XEiii
@end verbatim

If this is the case, the library libSherpaMain.so must be preloaded,
which can be achieved on a linux system via setting LD_PRELOAD
accordingly:
@verbatim
export LD_PRELOAD=<prefix>/lib/SHERPA-MC/libSherpaMain.so
@end verbatim

@example
@smallformat
@verbatiminclude Examples/API/ME2/test.py.in
@end smallformat
@end example
