@node MSSM
@subsection Minimal Supersymmetric Standard Model

The MSSM is implemented via UFO, cf. 
@uref{https://feynrules.irmp.ucl.ac.be/wiki/MSSM}.
In order to use this model, Sherpa must be installed with python support,
using @option{--enable-pyext}, as described in @xref{Installation}.
Once installed, the model is made available to Sherpa by running
@verbatim
  Sherpa-generate-model MODEL/MSSM
@end verbatim

