@set spires http://www-spires.dur.ac.uk/cgi-bin/spiface/hep/www?rawcmd=

@macro mycite{ref}
@set U\ref\ true
[@ref{\ref\, @value{K\ref\}}]
@end macro

@macro mybibformatjvle
@ifset journal
@b{@value{journal}}
@ifset eprint
@value{eprint}
@end ifset
@end ifset
@ifclear journal
@ifset eprint
[@value{eprint}]
@end ifset
@end ifset
@end ifclear
@end macro

@macro mybibitem{ref,key,author,title,journal,vol,year,pages,eprint}
@ifclear mybibout
@set K\ref\ \key\
@clear U\ref\
@end ifclear
@ifset U\ref\
@item
@anchor{\ref\}[\key\] \author\, @emph{\title\},
\journal\ @b{\vol\}\year\\pages\
[@uref{@value{spires}\eprint\,\eprint\}].
@sp 2
@end ifset
@end macro

@macro mybibbegin{filename}
@include \filename\
@end macro

@macro mybibend{filename,refname}
@node \refname\
@chapter \refname\
@itemize @asis
@set mybibout true
@include \filename\
@end itemize
@end macro
