@node Parameters
@chapter Parameters

A Sherpa run is steered by various parameters, associated with the
different components of event generation. These are set in 
@iftex 
S\scalebox{0.8}{HERPA}\xspace's 
@end iftex 
@ifnottex
Sherpa's
@end ifnottex 
configuration file, see @ref{Input structure} for more details. Tag
replacements may be
performed in all inputs, see @ref{Tags}.

@menu
* General Parameters::
* Beam Parameters::
* ISR Parameters::    Initial-state radiation
* Models::            Interaction models for the hard process
* Matrix Elements::
* Processes::
* Selectors::         Parton-level cuts
* Integration::
* Hard decays::
* Shower Parameters::
* MPI Parameters::    Multiple parton interactions
* Hadronization::
* QED Corrections::
* Minimum Bias::
@end menu

@include Run.texi
@include Beam.texi
@include ISR.texi
@include Models.texi
@include ME.texi
@include Processes.texi
@include Selector.texi
@include Integration.texi
@include HardDecays.texi
@include Shower.texi
@include MI.texi
@include Fragmentation.texi
@include SoftQED.texi
@include MinBias.texi

