@node Tevatron_DiBoson
@section Tevatron_DiBoson

@example
@smallformat
@verbatiminclude Examples/Tevatron_DiBoson/Run.dat
@end smallformat
@end example

This is a Tevatron set-up with two W bosons produced, 
and both decaying leptonically. Up to two jets are also 
included in the matrix element. 

Things to notice:
@itemize @bullet
@item in the @code{(model)} section, the top quark and 
Higgs have been turned off, using the @code{ACTIVE[PDG]}
switches.

@end itemize




