@node Tevatron_TopPair
@section Tevatron_TopPair

This set-up is very similar to the @ref{LHC_TopPair} example above.
There are two notable differences. Firstly, obviously this is a Tevatron
set-up with proton anti-proton collisions at Tevatron energies. 
Secondly, there are two allowed decay channels.

@example
@smallformat
@verbatiminclude ../Examples/Tevatron_TopPair/Run.dat
@end smallformat
@end example

The process generated is the production of a top pair from two light quarks, with 
possibly an extra final-state parton. Each top then decays into (anti-)bottom
quark and W+(-) boson. One of the W-bosons then decays leptonically, and 
the other decays to quarks. This time we include processes with either of 
the two W-bosons decaying leptonically, not just the W-, as in the
@ref{LHC_TopPair} example above.

Things to notice:
@itemize @bullet
@item there are two separate processes defined. Every different decay route
must have it's own process. It is not possible to group the different W-
decays into one top-production process. 

@end itemize

