@node Tevatron_QCD
@section Tevatron_QCD

This example generates QCD events at the Tevatron,
with 2, 3 or 4 final state partons in the matrix
element. A run card with an example
analysis set-up enabled is also included in this folder, and called 
@code{Run.analyse.dat}. This run card provides an example of using weighted
events with Sherpa, and the use of the @ref{Enhance_Observable} and
@ref{Enhance_Factor} tags. To use this run card, as it is not named @option{Run.dat}, 
the parameter @code{RUNDATA} must be specified on the command line,
see @ref{Input structure}.

@comment  @subsection Run.dat

@example
@smallformat
@verbatiminclude Examples/Tevatron_QCD/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item @code{Order_EW} is set to @option{0}. This
ensures that all final state jets are produced via 
the strong interaction.
@item an @code{NJetFinder} selector is used to 
set a resolution criterion for the two jets of the core process.
This is necessary because the `CKKW' tag does not apply any cuts to the core
process, but only to the extra-jet matrix elements, see @ref{Merging ME and PS}.
@end itemize
