@node Tevatron_ZJets_MENLOPS
@section Tevatron_ZJets_MENLOPS

This setup implements the MENLOPS method, combining both POWHEG-style 
NLO matrix element parton shower matching and CKKW-style multijet merging, 
cf. @mycite{Hoche2010kg}, @mycite{Hamilton2010wh}. Its result, after switching 
on both the hadronisation and underlying event modules, can then be directly 
compared to experimental data.

@example
@smallformat
@verbatiminclude Examples/Tevatron_ZJets_MENLOPS/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item This is a Tevatron Run II setup for inclusive Drell-Yan production, using 
the MENLOPS method.
@item The core process is calculated at NLO accuracy. The NLO part of setup is 
therefore similar to @ref{Tevatron_W_POWHEG}. Its scale is set to the 
transverse mass of the lepton pair.
@item Up to three additional jets are described by leading order matrix 
elements.
@item An internal hard-coded matrix element is used for the virtual term of the
Drell-Yan core process. For more information on how to interface 
@ref{External one-loop ME}s see the linked section. Higher order emissions 
are only described at tree-level.
@item @code{Enhance_Function} have been added to raise statistics on hard jet 
emissions.
@item Neither hadronisation nor underlying event corrections are taken into 
account. Both can be switched on by setting the relevant @ref{Parameters} 
accordingly.

@end itemize
