@node Tevatron_UE
@section Tevatron_UE

In this example, the underlying event has been switched on. The
parameters controlling the simulation of multiple interactions
can be set in the @code{(mi)} section of the run card. For a
full list of the available settings, see @ref{MPI Parameters}.


@example
@smallformat
@verbatiminclude Examples/Tevatron_UE/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item multiple interactions have been turned on, by setting
@ref{MI_HANDLER} to @option{Amisic}.

@item the transverse momentum cut-off @ref{SCALE_MIN} has been set
to 2.5GeV.

@end itemize

