@node Tevatron_WJets
@section Tevatron_WJets

The Tevatron W+jets set-up is very similar to the 
Z+jets example. The only differnces are in the 
final state leptons, and the invariant mass cuts on 
the lepton pairs. However, an analysis example has also
been included in this folder, providing examples
of Rivet analyses valid for W+jet production.

@subsection Run.dat

@verbatim
(processes){
  Process 93 93 -> 11 -12 93{3}
  Order_EW 2; Max_N_Quarks 6
  CKKW sqr(30/E_CMS)
  Integration_Error 0.1 {2};
  Integration_Error 0.2 {3};
  Integration_Error 0.3 {4};
  Integration_Error 0.4 {5};
  End process;

  Process 93 93 -> -11 12 93{3}
  Order_EW 2; Max_N_Quarks 6
  CKKW sqr(30/E_CMS)
  Integration_Error 0.1 {2};
  Integration_Error 0.2 {3};
  Integration_Error 0.3 {4};
  Integration_Error 0.4 {5};
  End process;
}(processes)

(selector){
  Mass -11 12 1.7 E_CMS
  Mass 11 -12 1.7 E_CMS
}(selector)
@end verbatim

@subsection Run.analyse.dat

@verbatim
(analysis){
  BEGIN_RIVET {
    -H NJETjet.QCUTGeV.ANATAG
    -a CDF_2008_S7541902
  } END_RIVET
}(analysis)
@end verbatim

Things to notice:
@itemize
@item the analysis used in this example is valid 
for W+jet production at the Tevatron, see the
@uref{http://projects.hepforge.org/rivet/,,Rivet Website} for more details.

@end itemize
