@node Tevatron_ZJets
@section Tevatron_ZJets

This set-up is very similar to the one above, for @ref{LHC_ZJets}, but with 
proton--anti-proton collisions at Tevatron energies.

@example
@smallformat
@verbatiminclude ../Examples/Tevatron_ZJets/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item the PDG code for an anti-proton @option{-2212} is minus the PDG
code for a proton @option{2212}.

@end itemize

