@node NLO_W
@section NLO_W

This example computes the next-to-leading W-production
cross section at Tevatron Run II energies. 

@example
@smallformat
@verbatiminclude Examples/NLO_W/Run.dat
@end smallformat
@end example

Things to notice:
@itemize @bullet
@item The results are generated exactly up to order alpha_S^1. 
It is not possible to attach parton showers or a
hadronization consistently to these pure NLO matrix elements. To perform 
a parton shower matched NLO calculation one of the following examples has to be 
invoked: @ref{LHC_WJets_MENLOPS}, @ref{Tevatron_ZJets_MENLOPS}, 
@ref{LHC_HWW_POWHEG}, @ref{LHC_HZZ_POWHEG}, @ref{LHC_HPP_POWHEG}.
@item This setup will generate 1e6 weighted events and and put
them into histograms for a few observables, reproducing the NLO 
data in Fig. 8 of @mycite{Gleisberg2007md}.
@item The process setup has been explicitly split into pieces
with born-like and with real-correction-like kinematics. 
It is possible to run the setup without this, however, usually
the phase space integration for the real correction is more
complicated and thus less efficient. To cope with this an 
@code{Enhance_Factor} has been added, see @ref{Processes}.
@item Sherpa's internal analysis package is used. Therefore,
when installing Sherpa the option
@code{--enable-analysis} must be include on the command line when
Sherpa is configured, see @ref{ANALYSIS}.
@item In order to correctly treat real correction contributions
within the internal analysis it must be set up with
@code{LEVEL MENLO}.
@item For more information on how to use the implemeted 
automated dipole subtraction for NLO calculations see @ref{Parameters},
@ref{NLO calculations} and @ref{External one-loop ME}.
 

@end itemize
