# - Try to find ggvvamp
# Defines:
#
#  GGVVAMP_FOUND
#  GGVVAMP_INCLUDE_DIR
#  GGVVAMP_INCLUDE_DIRS (not cached)
#  GGVVAMP_LIBRARY
#  GGVVAMP_LIBRARIES (not cached)
#  GGVVAMP_LIBRARY_DIR (not cached)

if (GGVVAMP_ROOT_DIR OR GGVVAMP_DIR OR (DEFINED ENV{GGVVAMP_ROOT_DIR}) OR (DEFINED ENV{GGVVAMP_DIR}) )
  set(GGVVAMP_SEARCH_DIRS "" CACHE STRING "" FORCE)
  if (GGVVAMP_ROOT_DIR)
    list (APPEND GGVVAMP_SEARCH_DIRS "${GGVVAMP_ROOT_DIR}" )
  endif()
  if (GGVVAMP_DIR)
    list (APPEND GGVVAMP_SEARCH_DIRS "${GGVVAMP_DIR}" )
  endif()
  if (DEFINED EVN{GGVVAMP_ROOT_DIR})
    list (APPEND GGVVAMP_SEARCH_DIRS "$ENV{GGVVAMP_ROOT_DIR}" )
  endif()
  if (DEFINED ENV{GGVVAMP_DIR})
    list (APPEND GGVVAMP_SEARCH_DIRS "ENV{GGVVAMP_DIR}" )
  endif()
endif()
if (GGVVAMP_SEARCH_DIRS)
  find_path(GGVVAMP_INCLUDE_DIR ggvvamp.h PATHS ${GGVVAMP_SEARCH_DIRS} PATH_SUFFIXES include include/ggvvamp NO_DEFAULT_PATH)
  find_library(GGVVAMP_LIBRARY NAMES ggvvamp PATHS ${GGVVAMP_SEARCH_DIRS}  PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
else()
  find_path(GGVVAMP_INCLUDE_DIR ggvvamp.h PATH_SUFFIXES ../include ../include/ggvvamp)
  find_library(GGVVAMP_LIBRARY NAMES ggvvamp PATHS_SUFFIXES ../lib ../lib64)
endif()

mark_as_advanced(GGVVAMP_INCLUDE_DIR GGVVAMP_LIBRARY)
get_filename_component(GGVVAMP_PATH ${GGVVAMP_INCLUDE_DIR} DIRECTORY)


if (NOT GGVVAMP_VERSION)
  set(GGVVAMP_VERSION Unknown)
endif()
include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(ggvvamp REQUIRED_VARS GGVVAMP_VERSION GGVVAMP_INCLUDE_DIR GGVVAMP_LIBRARY GGVVAMP_PATH
                           VERSION_VAR GGVVAMP_VERSION 
                                 )
set(GGVVAMP_LIBRARIES ${GGVVAMP_LIBRARY})
get_filename_component(GGVVAMP_LIBRARY_DIR ${GGVVAMP_LIBRARY} PATH)

set(GGVVAMP_INCLUDE_DIRS ${GGVVAMP_INCLUDE_DIR})

mark_as_advanced(ggvvamp_FOUND)
