# - Try to find LoopTools
# Defines:
#
#  LOOPTOOLS_FOUND
#  LOOPTOOLS_INCLUDE_DIR
#  LOOPTOOLS_LIBRARY
#  LOOPTOOLS_PREFIX
#
if (LOOPTOOLS_ROOT_DIR OR LOOPTOOLS_DIR OR LOOPTOOLS_DIRS OR
    (DEFINED ENV{LOOPTOOLS_ROOT_DIR}) OR (DEFINED ENV{LOOPTOOLS_DIR}) OR (DEFINED ENV{LOOPTOOLS_DIRS}))
  set(LOOPTOOLS_SEARCH_DIRS "" CACHE STRING "" FORCE)
  if (LOOPTOOLS_ROOT_DIR)
    list(APPEND LOOPTOOLS_SEARCH_DIRS "${LOOPTOOLS_ROOT_DIR}")
  endif()
  if (LOOPTOOLS_DIR)
    list(APPEND LOOPTOOLS_SEARCH_DIRS "${LOOPTOOLS_DIR}")
  endif()
  if (LOOPTOOLS_DIRS)
    list(APPEND LOOPTOOLS_SEARCH_DIRS "${LOOPTOOLS_DIRS}")
  endif()
  if (DEFINED ENV{LOOPTOOLS_ROOT_DIR})
    list(APPEND LOOPTOOLS_SEARCH_DIRS "$ENV{LOOPTOOLS_ROOT_DIR}")
  endif()
  if (DEFINED ENV{LOOPTOOLS_DIR})
    list(APPEND LOOPTOOLS_SEARCH_DIRS "$ENV{LOOPTOOLS_DIR}")
  endif()
  if (DEFINED ENV{LOOPTOOLS_DIRS})
    list(APPEND LOOPTOOLS_SEARCH_DIRS "$ENV{LOOPTOOLS_DIRS}")
  endif()
endif()

if (LOOPTOOLS_SEARCH_DIRS)
  find_path(LOOPTOOLS_INCLUDE_DIR clooptools.h PATHS ${LOOPTOOLS_SEARCH_DIRS} PATH_SUFFIXES include NO_DEFAULT_PATH)
  find_library(LOOPTOOLS_LIBRARY NAMES ooptools PATHS ${LOOPTOOLS_SEARCH_DIRS} PATH_SUFFIXES lib lib64 NO_DEFAULT_PATH)
else()
  find_path(LOOPTOOLS_INCLUDE_DIR clooptools.h PATH_SUFFIXES include ../include)
  find_library(LOOPTOOLS_LIBRARY NAMES ooptools PATH_SUFFIXES lib lib64 ../lib ../lib64)
endif()

if (LOOPTOOLS_LIBRARY)
  get_filename_component(T_PATH ${LOOPTOOLS_LIBRARY} DIRECTORY)
  get_filename_component(LOOPTOOLS_PREFIX ${T_PATH} DIRECTORY)
endif()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LoopTools REQUIRED_VARS LOOPTOOLS_LIBRARY LOOPTOOLS_INCLUDE_DIR LOOPTOOLS_PREFIX)

if (LoopTools_FOUND AND NOT TARGET LoopTools::LoopTools)
  add_library(LoopTools::LoopTools UNKNOWN IMPORTED)
  set_target_properties(LoopTools::LoopTools PROPERTIES
    IMPORTED_LOCATION "${LOOPTOOLS_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${LOOPTOOLS_INCLUDE_DIR}"
  )
endif()

mark_as_advanced(LoopTools_FOUND LOOPTOOLS_INCLUDE_DIR LOOPTOOLS_LIBRARY)
