#!/bin/bash

DIRS="ATOOLS BEAM PDF MODEL PHASIC++"
DIRS=$DIRS" EXTRA_XS COMIX APACIC++ CSSHOWER++"
DIRS=$DIRS" AMEGIC++ AMISIC++ ANALYSIS"
DIRS=$DIRS" HADRONS++ SHERPA"

EXTENSIONS="\.C \.cpp \.cc"
EXTENSIONS=$EXTENSIONS" \.H \.hpp \.hh"
EXTENSIONS=$EXTENSIONS" \.am configure\.in" 
EXTENSIONS=$EXTENSIONS" \.trf \.texi"
DESCRIPTIONS="C-Files cpp-Files cc-Files"
DESCRIPTIONS=$DESCRIPTIONS" H-Files hpp-Files hh-Files"
DESCRIPTIONS=$DESCRIPTIONS" Makefiles configures"
DESCRIPTIONS=$DESCRIPTIONS" Manpages TeXinfos"
COLOURS="4 4 4 2 2 2 1 1 6 6"

OPTIONS=
for I in $* ; do
  if [ "$I" = "-o" ]; then ONE=TRUE
  elif [ "$I" = "-h" ]; then echo && \
    echo "codestatistics version 1.0" && echo && \
    echo "         -o             examine single module" && \
    echo "options: -h             display this help and exit" && \
    echo && exit 0
  else echo "codestatistics: unknown option '"$I"'. try '-h'" && \
    exit 1
  fi
done

if [ "$ONE" = "TRUE" ] ; then 
  echo "makeinstall: select module ( q) to quit )"
  select DIRS in $DIRS ; do
    if [ "$DIRS" != "" ] ; then 
      break
    else 
      if [ "$REPLY" = "q" ] || [ "$REPLY" = "Q" ]  ; then exit ; fi
    fi
  done
fi

AFCOUNT=0
ACCOUNT=0
for DIR in $DIRS ; do
  echo -e "\e[31m**************************************************\e[0m"
  echo -en "\e[31m*                                                *\e[0m"
  echo -e "\r\e[31m*\e[0m\e[1m $DIR \e[0m"
  echo -e "\e[31m**************************************************\e[0m"
  EXTCNT=0
  TFCOUNT=0
  TCCOUNT=0
  TLCOUNT=0
  for EXTENSION in $EXTENSIONS ; do
    (( ++EXTCNT ))
    DESCCNT=0
    for DESCRIPTION in $DESCRIPTIONS ; do
      (( ++DESCCNT ))
      if (( $DESCCNT == $EXTCNT )) ; then break ; fi
    done
    COLCNT=0
    for COLOUR in $COLOURS ; do
      (( ++COLCNT ))
      if (( $COLCNT == $EXTCNT )) ; then break ; fi
    done
    echo -en "\e[1m==================================================\e[0m"
    echo -e "\r\e[1m=\e[3"$COLOUR"m $DESCRIPTION \e[0m"
    FCOUNT=`find $DIR -name *$EXTENSION | wc -l`
    (( TFCOUNT = TFCOUNT + FCOUNT ))
    echo -e "Files   : $FCOUNT" 
    if (( $FCOUNT != 0 )); then
      LCOUNT=`cat \`find $DIR -name *$EXTENSION\` | wc -l`
      (( TLCOUNT = TLCOUNT + LCOUNT ))
      CCOUNT=`grep class \`find $DIR -name *.H\`  | grep "{" | wc -l`
      (( TCCOUNT = TCCOUNT + CCOUNT ))
    else
      LCOUNT=0
      CCOUNT=0
    fi
    echo -e "Lines   : $LCOUNT" 
  done
  (( AFCOUNT = AFCOUNT + TFCOUNT ))
  (( ACCOUNT = ACCOUNT + TCCOUNT ))
  (( ALCOUNT = ALCOUNT + TLCOUNT ))
  echo -en "\e[1m==================================================\e[0m"
  echo -e "\r\e[1m=\e[34m Module \e[0m"
  echo -e "Files   : $TFCOUNT"
  echo -e "Lines   : $TLCOUNT"
  echo -e "Classes : $TCCOUNT"
  echo -e "\e[1m==================================================\e[0m"
done
echo -en "\n\e[1m==================================================\e[0m"
echo -e "\r\e[1m=\e[34m Total \e[0m"
echo -e "Files   : $AFCOUNT"
echo -e "Lines   : $ALCOUNT"
echo -e "Classes : $ACCOUNT"
echo -e "\e[1m==================================================\e[0m"

# mode:shell-script
# sh-indentation:2

