#!/bin/bash

EXTENSIONS="\.C \.cpp \.cc"
EXTENSIONS=$EXTENSIONS" \.H \.hpp \.hh"
EXTENSIONS=$EXTENSIONS" \.am configure\.in" 
EXTENSIONS=$EXTENSIONS" \.trf \.man \.texi \.info"
DESCRIPTIONS="C-Files cpp-Files cc-Files"
DESCRIPTIONS=$DESCRIPTIONS" H-Files hpp-Files hh-Files"
DESCRIPTIONS=$DESCRIPTIONS" Makefiles configures"
DESCRIPTIONS=$DESCRIPTIONS" Manpages Manpages TeXinfos TeXinfos"
COLOURS="4 4 4 2 2 2 1 1 6 6 6 6"

OPTIONS=
for I in $* ; do
  if [ "$I" = "-h" ]; then echo && \
    echo "codestatistics version 1.0" && echo && \
    echo "options: -h             display this help and exit" && \
    echo && exit 0
  else echo "codestatistics: unknown option '"$I"'. try '-h'" && \
    exit 1
  fi
done

TFCOUNT=0
TCCOUNT=0
for EXTENSION in $EXTENSIONS ; do
  (( ++EXTCNT ))
  DESCCNT=0
  for DESCRIPTION in $DESCRIPTIONS ; do
    (( ++DESCCNT ))
    if (( $DESCCNT == $EXTCNT )) ; then break ; fi
  done
  COLCNT=0
  for COLOUR in $COLOURS ; do
    (( ++COLCNT ))
    if (( $COLCNT == $EXTCNT )) ; then break ; fi
  done
  echo -en "\e[1m==================================================\e[0m"
  echo -e "\r\e[1m=\e[3"$COLOUR"m $DESCRIPTION \e[0m"
  FCOUNT=`find . -name *$EXTENSION | wc -l`
  (( TFCOUNT = TFCOUNT + FCOUNT ))
  echo -e "Files   : $FCOUNT" 
  LCOUNT=`cat \`find . -name *$EXTENSION\` | wc -l`
  (( TLCOUNT = TLCOUNT + LCOUNT ))
  echo -e "Lines   : $LCOUNT" 
done
echo -en "\e[1m==================================================\e[0m"
echo -e "\r\e[1m=\e[34m Total \e[0m"
CCOUNT=`grep class \`find . -name *.H\`  | grep "{" | wc -l`
echo -e "Files   : $TFCOUNT"
echo -e "Lines   : $TLCOUNT"
echo -e "Classes : $CCOUNT"
echo -e "\e[1m==================================================\e[0m"

# mode:shell-script
# sh-indentation:2

