#!/bin/bash

DATS="Beam.dat Decays.dat Fragmentation.dat Hadron.dat Integration.dat"
DATS=$DATS" ISR.dat Lund.dat ME.dat MI.dat Model.dat Particle.dat"
DATS=$DATS" Processes.dat Run.dat Selector.dat Shower.dat"
DATS=$DATS" Analysis.dat.C"

for I in $* ; do
  if [ "$I" = "-h" ] ; then DDPATH=FALSE && echo && \
    echo "diffruns version 1.0" && echo && \
    echo "options: -h             display this help and exit" && \
    echo "         <any other>    directories to diff" && echo && \
    exit 0
  elif [ "$DDPATH" != "FALSE" ] ; then DDPATH="" && DPATHS=$DPATHS" "$I
  fi
done

I=0
for DPATH in $DPATHS ; do
  (( ++I ))
  if (( $I > 1 )) ; then
    echo
    for DAT in $DATS ; do
      DIFF=`diff -b $REF/$DAT $DPATH/$DAT`
      if [ "$DIFF" != "" ] ; then 
        echo "==> $DAT '$REF' vs. '$DPATH' <=="
        diff -b $REF/$DAT $DPATH/$DAT
        echo
      fi
    done
    DIFF=`diff $REF/$REF.sh $DPATH/$DPATH.sh | grep Sherpa`
    if [ "$DIFF" != "" ] ; then 
      echo "==> startscript '$REF' vs. '$DPATH' <=="
      diff $REF/$REF.sh $DPATH/$DPATH.sh | grep Sherpa
      echo
    fi
  else
    REF=$DPATH
  fi
done

