#!/bin/bash

NODES="ptpp90 ptpp91 ptpp92 ptpp93 ptpp86 ptpp87 ptpp88"
HOSTN=`hostname`

echo -e "\e[34m\e[1mstatus report:\e[0m `date`"

for I in $NODES
do
 if [[ $HOSTN == $I ]]
 then
  echo -en "\e[1m$I (local) :\e[0m\e[32m"
  uptime
  echo -en "\e[0m\e[31m"
  ps -fA | grep "Sherpa" 
  echo -en "\e[0m"
 else
  echo -en "\e[1m$I :\e[0m\e[32m"
  ssh $I uptime
  echo -en "\e[0m\e[31m"
  ssh $I ps -fA | grep "Sherpa" 
  echo -en "\e[0m"
 fi
done
echo -en "\e[0m"

