#!/bin/bash

ECOPT=""

print_help() {
  echo "makedist version 1.0 " && echo && \
  echo "options: -f             include full time information in distribution name" && \
  echo "         -n <name>      write compressed distribution to <name>.tar.gz (default: Sherpa-X.X.X)" && \
  echo "         --clean        execute 'make clean' before 'make dist'" && \
  echo "         --configure    configure before 'make dist' (enabled with '--total')" && \
  echo "         --total        rebuild 'Makefile.in's' and 'configure's' before 'make dist'" && \
  echo "         --copt         define option for 'configure'" && \
  echo "         --exclude-svn  exclude .svn directories (only necessary when they exist)" && \
  echo "         --release      prepare for release in copied tree: svn update, module renaming, --total" && \
  echo "                        Warning: This may use much disk space, because it makes a copy of the file tree." && \
  echo "         -h             display this help and exit" && \
  echo
}

VERSION="$(cat configure.in | grep "AC_INIT" | cut -d"," -f 2 | tr -d " ")";
DISTDIR="Sherpa-"$VERSION;

while getopts :hfun: OPT
do
  case $OPT in
  f) DISTDIR=$DISTDIR"_"$(date +'%Y-%m-%d_%H-%M') ;;
  n) DISTDIR=$OPTARG ;;
  h) print_help && exit 0 ;;
  \?)
    shift `expr $OPTIND - 1`
    if [ "$1" = "--clean" ]; then ALLCLEAN=TRUE 
    elif [ "$1" = "--configure" ]; then CONFIGURE=TRUE 
    elif [ "$1" = "--exclude-svn" ]; then EXCLUDESVN=TRUE
    elif [ "$1" = "--total" ]; then TOTAL=TRUE && CONFIGURE=TRUE
    elif [ "$1" = "--copt" ]; then 
      CONFIGURE=TRUE && ECOPT=$2" "$ECOPT && shift 1
    elif [ "$1" = "--release" ]; then RELEASE=TRUE && TOTAL=TRUE && EXCLUDESVN=TRUE && CONFIGURE=TRUE
    else 
      echo -n "makedist: error: unrecognized option "
      if [ $OPTARG != "-" ]; then echo "'-$OPTARG'. try '--help'"
      else echo "'$1'. try '--help'"
      fi
      print_help && exit 1
    fi
    shift 1
    OPTIND=1
  esac
done

if [ "$EXCLUDESVN" = "TRUE" ]; then 
  ECOPT=$ECOPT" --disable-svninclude" && CONFIGURE=TRUE;
else
  if ! test -d ".svn"; then
    ECOPT=$ECOPT" --disable-svninclude" && CONFIGURE=TRUE;
  fi
fi

echo "*************************************"
echo "*  creating distribution of SHERPA  *"
echo "*************************************"


if [ "$RELEASE" = "TRUE" ]; then
  SUBSUBV=$(echo $VERSION | cut -d "." -f 3)
  if test -d "../makedist"; then
    echo "Directory ../makedist already exists. Please remove and retry."
    exit 1;
  fi
  mkdir ../makedist;
  echo -e "  copying file tree to temporary directory ../makedist (this might take a while)"
  cp -rp $(pwd) ../makedist/;
  cd ../makedist/$(basename $(pwd));

  if test -x "$(which svn)" && test ! "$(svn status -q)" = ""; then 
    echo "The copy of your version has local modifications:"
    svn status -q
    echo "Are you sure, you want to create a release tarball from that?"

      until [ "$CONTINUE" = "c" ]; do
        if ! read -t 300 -n 1 -p "(c)ontinue / (r)evert local modifications and continue / (a)bort) ? " CONTINUE ; then
          CONTINUE="c"
        fi
        echo ""
        if [ "$CONTINUE" = "a" ]; then
          exit 1
        elif [ "$CONTINUE" = "r" ]; then
          svn revert --recursive .
          CONTINUE="c"
        fi
      done

  fi
  svn update

  ## rename modules in working copy
  echo -e "  renaming modules in working copy";
  MODULES=*".0";
  for I in $MODULES; do
    mv $I $I"."$SUBSUBV
  done;
  MFS=`find . -name Makefile.am`
  for I in $MFS; do
    sed -e 's/-0.0/-0.0.'$SUBSUBV'/g' < $I > $I.new
    sed -e 's/-1.0/-1.0.'$SUBSUBV'/g' < $I.new > $I.new2
    sed -e 's/-2.0/-2.0.'$SUBSUBV'/g' < $I.new2 > $I.new
    mv $I.new $I
    rm $I.new2
  done
  MFS="TOOLS/makeinstall configure.in acinclude.m4"
  for I in $MFS; do
    sed -e 's/-0.0/-0.0.'$SUBSUBV'/g' < $I > $I.new
    sed -e 's/-1.0/-1.0.'$SUBSUBV'/g' < $I.new > $I
    sed -e 's/-2.0/-2.0.'$SUBSUBV'/g' < $I > $I.new
    mv $I.new $I
  done;
fi
if [ "$TOTAL" = "TRUE" ]; then
  cp INSTALL INSTALL.Sherpa;
  autoreconf -fi
  mv INSTALL.Sherpa INSTALL;
fi
if [ "$CONFIGURE" = "TRUE" ]; then
  ./configure $ECOPT;
fi
if [ "$ALLCLEAN" = "TRUE" ]; then
  make clean
fi

make distdir;

if [ "$RELEASE" = "TRUE" ]; then
  # add sample runs to distdir
  ###########################################################
  cd SHERPA-MC-$VERSION;
  SAMPLERUNS="Tevatron1800 LHC EGamma LEP91";
  for I in $SAMPLERUNS ; do
    cp -r ../SHERPA-$VERSION/Run/$I SHERPA-$VERSION/Run/;
    rm -rf SHERPA-$VERSION/Run/$I/.svn;
    rm -rf SHERPA-$VERSION/Run/$I/*~;
    rm -rf SHERPA-$VERSION/Run/$I/xsections*;
    rm -rf SHERPA-$VERSION/Run/$I/*weight*;
    rm -rf SHERPA-$VERSION/Run/$I/makelibs;
    rm -rf SHERPA-$VERSION/Run/$I/Process;
    rm -rf SHERPA-$VERSION/Run/$I/Results;
    rm -rf SHERPA-$VERSION/Run/$I/Status__*;
  done;
  ###########################################################
  cd ..;
fi

## prepare scripts
chmod 755 TOOLS/makeinstall;
## remove ATOOLS/Org/CXXFLAGS.H
rm SHERPA-MC-$VERSION/*/*/CXXFLAGS.H
## tar it
tar -czhf "$DISTDIR.tar.gz" SHERPA-MC-$VERSION/;
rm -rf SHERPA-MC-$VERSION/;
if [ "$RELEASE" = "TRUE" ]; then
  mv "$DISTDIR.tar.gz" ../../;
  cd ../..;
  rm -rf makedist;
fi

echo -e "\nwrote distribution to '$DISTDIR".tar.gz"'\n"
exit 0

# mode:shell-script
# sh-indentation:2
