#! /usr/bin/env python

from optparse import OptionParser, OptionGroup
import os, fnmatch
from subprocess import Popen, PIPE


usage = """Webpages from histogram files written out by Rivet.

Examples:
  source /path/to/rivetenv.sh
  %prog [options] <aidafile> [<aidafile> ...]
"""


parser = OptionParser(usage=usage)
parser.add_option("-o", "--outputdir", dest="OUTPUTDIR",
                  default="./", help="directory for webpage output.")

opts, aidafiles = parser.parse_args()

datadir = Popen(["rivet-config", "--datadir"], stdout=PIPE).communicate()[0].split()[0]



## get set of analyses involved in the runs
analyses = set()
for aidafile in aidafiles:
    anas = Popen('if test -f %s; then cat %s | grep path= | cut -d \\" -f 4 | uniq; fi' % (aidafile, aidafile), shell=True, stdout=PIPE).communicate()[0].split()
    for ana in anas:
        analyses.add(ana[1:])

index = open("index.html", "w")

for analysis in sorted(analyses):
    anapath = os.path.join(opts.OUTPUTDIR, analysis)
    os.mkdir(anapath)
    anaindex = open(os.path.join(anapath, "index.html"), 'w')
    anaindex.write("<html>\n")
    cmdargs = ["compare-histos"]
    cmdargs.append("--mc-errs")
    cmdargs.append("%s/%s.aida" % (datadir, analysis))
    for aidafile in aidafiles:
        cmdargs.append("../%s" % aidafile)
    Popen(cmdargs, cwd=anapath).wait()
    for datfile in os.listdir(anapath):
        if datfile=="index.html":
            continue
        if not fnmatch.fnmatch(datfile, analysis+"*.dat"):
            os.unlink(os.path.join(anapath, datfile))
            continue
        psfile = datfile.replace(".dat", ".ps")
        pngfile = datfile.replace(".dat", ".png")
        Popen(["make-plots", datfile], cwd=anapath).wait()
        Popen(["convert", "-density", "100", psfile, pngfile], cwd=anapath)
        anaindex.write('<div style="float:left;">')
        anaindex.write('<a href="%s" style="font-size:small;text-decoration:none;font-weight:bold;">' % psfile)
        anaindex.write('%s:<br><img border="0" src="%s"></a></div>\n' % (psfile, pngfile))
    anaindex.write("</html>\n")
    index.write('<h1><a href="%s/index.html" style="text-decoration:none;">%s</a></h1>\n' %(analysis, analysis))
    description = Popen(["rivet", "--show-analysis", analysis], stdout=PIPE).communicate()[0]
    index.write('<pre>%s</pre></li>\n' % description)
