#!/bin/bash

export LANG=en_US

print_help() {
    echo "memguard version 1.0" && echo && \
    echo "usage: memguard [options] process" && echo && \
    echo "options: -a <limit>  set absolute limit in kB" && \
    echo "         -r <limit>  set limit relative to available memory" && \
    echo "         -i <time>   check time interval" && \
    echo "         -o <time>   output time interval" && \
    echo "         -s <signal> kill nasty jobs with signal <signal>" && \
    echo "         -h          display this help and exit" && echo
}

SIGNAL=19
LIMIT=0.9
RELATIVE=TRUE
INTERVAL=1
OUTPUT=10
while getopts a:r:i:o:s:h OPT
do
  case $OPT in
  a) RELATIVE=FALSE; LIMIT=$OPTARG ;;
  r) RELATIVE=TRUE; LIMIT=$OPTARG ;;
  i) INTERVAL=$OPTARG ;;
  o) OUTPUT=$OPTARG ;;
  s) SIGNAL=$OPTARG ;;
  h) print_help && exit 0 ;;
  \?)
    shift `expr $OPTIND - 1`
    if [ "$1" = "--help" ]; then print_help && exit 0
    else 
      echo "memguard: error: unrecognized option '$1'."
      print_help && exit 1
    fi
    shift 1
    OPTIND=1
  esac
done

CNT=0
COMMAND=""
for I in $*; do
  if (( ++CNT > 0 )); then
    COMMAND=$COMMAND"`echo $I | awk '{ 
      if (match($0,\"-\")!=1) printf \" \"$0; }'`"
  fi
done
if [ "$COMMAND" = "" ]; then
  echo "memguard: empty command. stop."
  exit 1
fi

echo -n "memguard: check memory information ... "
if ! test -f /proc/meminfo; then
  echo "not found. stop."
  exit 1
fi
HARDLIMIT=`cat /proc/meminfo | grep MemFree | awk '{ printf $2; }'`
SYSLIMIT=`cat /proc/meminfo | grep MemTotal | awk '{ printf $2; }'`
echo $HARDLIMIT" kB free ( "$SYSLIMIT" kB total )"

SOFTLIMIT=HARDLIMIT
if [ "$RELATIVE" = "TRUE" ]; then
  SOFTLIMIT=`echo "scale=3; $LIMIT*$HARDLIMIT" | bc -q`
else
  SOFTLIMIT=$LIMIT
  LIMIT=`echo "scale=3; $SOFTLIMIT/$HARDLIMIT" | bc -q`
fi
if [ "`echo \"scale=6; $SOFTLIMIT>$HARDLIMIT\" | bc -q`" = "1" ]; then
  if [ "`echo \"scale=6; $SOFTLIMIT>$SYSLIMIT\" | bc -q`" = "1" ]; then
    echo "memguard: error: $SOFTLIMIT kB exceed total memory. stop."
    exit 1
  fi
  read -t 60 -p "memguard: warning: $SOFTLIMIT kB exceed \
free memory. continue (y/n) ? " CONT
  if [ "$CONT" != "y" ]; then 
    exit
  fi
fi

PRINTV=`echo "scale=2; $LIMIT*100" | bc -q`
echo "memguard: setting limit $SOFTLIMIT kB ( $PRINTV % )"
echo "memguard: check time interval $INTERVAL s"
echo "memguard: executing '$COMMAND'"

$COMMAND &

PROC=$!
echo "memguard: process started as pid $PROC"

( declare -i LTIME CTIME
  LTIME=`echo | awk '{ print systime(); }'`
  while (( 1 )); do
    if ! test -f /proc/$PROC/status; then
      echo "memguard: process $PROC terminated"
      exit 0
    fi
    CMEM=`cat /proc/$PROC/status | grep VmSize | awk '{ printf $2; }'`
    if [ "`echo \"scale=6; $CMEM>$SOFTLIMIT\" | bc -q`" = "1" ]; then
      kill -$SIGNAL $PROC
      echo "memguard: process $PROC stopped with signal $SIGNAL \
at vmem = $CMEM kB"
      exit 0
    fi
    CTIME=`echo | awk '{ print systime(); }'`
    if (( CTIME >= LTIME+OUTPUT )); then
      echo "memguard: process $PROC runs `ps ho \"%x\" $PROC` hrs, \
consumes $CMEM kB, limit is $SOFTLIMIT kB"
      LTIME=CTIME
    fi
    sleep $INTERVAL
  done ) &

