#!/bin/bash

echo "==============================================================="
for I in /proc/* ; do
  if test -d $I ; then
    if test -f $I/status ; then
      PID=`echo $I | sed 'sa/proc/aag'`
      SUID=`cat $I/status | grep Uid | awk '{print $2}'`
      SUNAME=`cat /etc/passwd | grep :$SUID: | sed 's/:x:/ /g' | awk '{print $1}'`
      NAME=`cat $I/status | grep Name | awk '{ print $2 }'`
      VMSIZE=`cat $I/status | grep VmSize | awk '{ print $2 }'`
      STATE=`cat $I/status | grep State | awk '{ print $2 }'`
      SLEEPAVG=`cat $I/status | grep SleepAVG | awk '{ print $2 }'`
      echo -e "$PID\r\e[10C$NAME\r\e[30C$VMSIZE\r\e[40C$STATE\r\e[45C$SLEEPAVG" \
	      "\r\e[50C$SUID\r\e[55C$SUNAME"
    fi
  fi
done
echo "==============================================================="
