#!/bin/bash
# 
# To successfully employ this script, make sure that your bash 
# is in the bin - directory or adjust accordingly.
#

DIRS="ATOOLS-2.0 PDF-1.0 BEAM-1.0 MODEL-1.0 EXTRA_XS-1.0"
DIRS=$DIRS" PHASIC++-1.0 APACIC++-2.0 AMEGIC++-2.0"
#DIRS=$DIRS" AMISIC++-1.0 ADICIC++-1.0"
DIRS=$DIRS" SHERPA-1.0"

for I in $* ; do
  if [ "$I" = "-c" ]; then CONFIGURE=TRUE 
  elif [ "$I" = "-i" ]; then INSTALL=TRUE 
  elif [ "$I" = "-h" ]; then \
    echo "rmlibs options: -c             configure before compiling" && \
    echo "                -i             \"make install\" after removing libraries" && \
    echo "                -h             display this help and exit" && \
    exit 0
  else echo "rmlibs: error: unrecognized option $I" && exit 1 ;
  fi
done

echo "**************************************"
echo "*   removing libraries from SHERPA   *"
echo "**************************************"
for I in $DIRS;
do
  echo "======================================"
  echo " removing libraries in $I;"
  echo "======================================"
  cd $I 
  FILES=`find . -maxdepth 4 -name 'lib*'`
  rm $FILES
  if test "$CONFIGURE" = "TRUE" ; then
    libtoolize --force
    aclocal
    automake -a
    autoconf
  fi
  if test "$INSTALL" = "TRUE" ; then
    make install -j2 
  fi
  cd ..
done;

