#!/bin/bash
TIME=`date +'%m-%d_%H-%M-%S'`

rmr () {  
  for file in * ; do                                                          
    if [ -d $file ] ; then                                                       
      cd $file                                                                  
      rmr "$1" $2
      cd ..                                                             
    fi
  done  
  for i in $1 ; do    
    rm -f $2 $i                                                                         
  done
}                                                                               

RUNPATH=""
RUNFILE=""
BINPATH=""
RESULTS=""
ANALYSIS=""
BASENAME=""
PYTHIA=""
for I in $* ; do
  if [ "$I" = "-p" ]; then DRUNPATH=TRUE 
  elif [ "$I" = "-f" ]; then DRUNFILE=TRUE 
  elif [ "$I" = "-b" ]; then DBINPATH=TRUE 
  elif [ "$I" = "-r" ]; then DRESULTS=TRUE 
  elif [ "$I" = "-a" ]; then DANALYSIS=TRUE 
  elif [ "$I" = "-e" ]; then DEVENTS=TRUE 
  elif [ "$I" = "-n" ]; then DBASENAME=TRUE 
  elif [ "$I" = "-q" ]; then QUEUE=TRUE 
  elif [ "$I" = "-P" ]; then DPYTHIA=TRUE 
  elif [ "$I" = "-h" ]; then echo && \
    echo "run version 1.0" && echo && \
    echo "options: -p <path>      read configuration from path <path>" && \
    echo "         -f <file>      read basic configuration from file <file>" && \
    echo "         -b <binpath>   take executeable from path <binpath>" && \
    echo "         -r <results>   write results to path <path>/<results>" && \
    echo "         -e <events>    generate <events> events" && \
    echo "         -a <analysis>  write analysis output to path <path>/<analysis>" && \
    echo "         -n <name>      set basic filename to <name>" && \
    echo "         -q             submit job to batch system" && \
    echo "         -P <file>      generate pythia events according to <file>" && \
    echo "         -h             display this help and exit" && echo && \
    exit 0
  elif [ "$DRUNPATH" = "TRUE" ]; then DRUNPATH="" && RUNPATH=$I
  elif [ "$DRUNFILE" = "TRUE" ]; then DRUNFILE="" && RUNFILE=$I
  elif [ "$DBINPATH" = "TRUE" ]; then DBINPATH="" && BINPATH=$I
  elif [ "$DRESULTS" = "TRUE" ]; then DRESULTS="" && RESULTS=$I
  elif [ "$DANALYSIS" = "TRUE" ]; then DANALYSIS="" && ANALYSIS=$I
  elif [ "$DBASENAME" = "TRUE" ]; then DBASENAME="" && BASENAME=$I
  elif [ "$DEVENTS" = "TRUE" ]; then DEVENTS="" && EVENTS=$I
  elif [ "$DPYTHIA" = "TRUE" ]; then DPYTHIA="" && PYTHIA=$I
  else echo "run: error: unrecognized option '$I'. try '-h'" && \
    exit 1 
  fi
done
if [ "$RUNPATH" = "" ]; then RUNPATH="./" ; fi
if [ "$RUNFILE" = "" ]; then RUNFILE="Run.dat" ; fi
if [ "$BINPATH" = "" ]; then BINPATH="./" ; fi
if [ "$RESULTS" = "" ]; then RESULTS="./" ; fi
if [ "$ANALYSIS" = "" ]; then ANALYSIS="./" ; fi
if [ "$BASENAME" = "" ]; then BASENAME="job" ; fi

LOGPATH=$PWD
SETUPPATH=$LOGPATH"/"$BASENAME"_"$TIME"/"
LOGFILE="run.log"
FILE=$BASENAME"_"$TIME".sh"

cp -r $RUNPATH $SETUPPATH
echo "" > $FILE
if [ "$QUEUE" = "TRUE" ] ; then 
  echo "#$ -j y" >> $FILE
  echo "#$ -o $SETUPPATH" >> $FILE
  echo "#$ -N $FILE.sge" >> $FILE
  echo "" >> $FILE
  echo "RUNPATH=$SETUPPATH" >> $FILE
  echo "LOGFILE=\$SETUPPATH\"$LOGFILE\"" >> $FILE
  echo "" >> $FILE
  echo "echo \"\" > \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"HOSTNAME    = \$HOSTNAME\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"HOME        = \$HOME\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"USER        = \$USER\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"QUEUE       = \$QUEUE\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"SGE_TASK_ID = \$SGE_TASK_ID\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"JOB_ID      = \$JOB_ID\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"JOB_NAME    = \$JOB_NAME\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"TMPDIR      = \$TMPDIR\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "echo \"\" >> \$RUNPATH\$LOGFILE" >> $FILE
  echo "" >> $FILE
else
  echo "#!/bin/bash" >> $FILE
  echo "" >> $FILE
  echo "LOGFILE=$LOGFILE" >> $FILE
  echo "" >> $FILE
fi
echo "cd $BINPATH" >> $FILE
echo -en "./Sherpa PATH=\$RUNPATH " >> $FILE
if [ ! "$RUNFILE" = "" ] ; then echo -en "RUNDATA=$RUNFILE " >> $FILE ; fi
if [ ! "$RESULTS" = "" ] ; then echo -en "RESULTS=\$RUNPATH\"$RESULTS\" " >> $FILE ; fi
if [ ! "$ANALYSIS" = "" ] ; then echo -en "ANALYSIS_OUTPUT=\$RUNPATH\"$ANALYSIS\" " >> $FILE ; fi
if [ ! "$EVENTS" = "" ] ; then echo -en "EVENTS=$EVENTS " >> $FILE ; fi
if [ ! "$PYTHIA" = "" ] ; then echo -en "PYTHIA=$PYTHIA " >> $FILE ; fi
echo -e ">> \$RUNPATH\$LOGFILE 2>&1 \n\n" >> $FILE

if [ "$QUEUE" = "TRUE" ] ; then
  qsub $FILE  
else
  chmod 777 $FILE
  ( nohup $FILE > /dev/null & ) 
fi
mv $FILE $SETUPPATH

# mode:shell-script
# sh-indentation:2
