#!/bin/bash
SLEEP=120
if [ "$1" != "" ] ; then
  SLEEP=$1
fi
sleep $SLEEP 
echo -e "\e[34m********************************************"
echo -e "*\e[0m\a\e[5m\e[31m            The tea is ready\e[0m              \e[34m*"
echo -e "********************************************\e[0m"
for ((i=0;i<25;++i)) ; do 
  sleep '1e-1s' 
  echo -en "\a"
done

