#!/bin/bash

export LANG=en_US

declare -a FNAME1 FNAME2

FILE1=#___xs_comparison___#

CNT=0
while read LINE; do
 FNAME1[CNT]=`echo $LINE | awk '{ print $1; }'`
 FNAME2[CNT]=`echo $LINE | awk '{ print $2; }'`
 if [ "${FNAME1[CNT]}" != "" ] && [ "${FNAME2[CNT]}" != "" ]; then 
   if (( CNT == 0 )); then
     echo "$LINE" > $FILE1
   fi
   (( ++CNT ))
 fi
done
for (( i=1; i<$CNT; ++i )); do
  cat ${FNAME1[i]} >> $FILE1
done
echo "end" >> $FILE1
for (( i=1; i<$CNT; ++i )); do
  cat ${FNAME2[i]} >> $FILE1
done
echo "end" >> $FILE1

awk -f testxs.awk < $FILE1

rm $FILE1

