#!/bin/bash

NOUPDATE="TRUE"
TEMPFILE="#update#"

EXTENSIONS="C H am"
DESCRIPTIONS="C-Files H-Files Makefiles"
COLOURS="4 2 1"

OPTIONS=
LOGFILE="updated"
for I in $* ; do
  if [ "$I" = "-n" ]; then NOUPDATE=TRUE 
  elif [ "$I" = "-f" ]; then NOUPDATE=
  elif [ "$I" = "-l" ]; then DLOGFILE=TRUE && CLOGFILE=TRUE
  elif [ "$I" = "-h" ]; then echo && \
    echo "update version 1.0" && echo && \
    echo "options: -n             run 'cvs -n update <options>'" && \
    echo "         -f             run 'cvs update <options>'" && \
    echo "         -l <logfile>   create logfile <logfile>" && \
    echo "         -h             display this help and exit" && \
    echo "         <any other>    passed directly to 'cvs update'" && echo && \
    exit 0
  elif [ "$DLOGFILE" = "TRUE" ]; then DLOGFILE="" && LOGFILE=$I
  else OPTIONS=$OPTIONS" "$I
  fi
done

if [ "$NOUPDATE" = "TRUE" ] ; then 
  if ! cvs -n update $OPTIONS > $LOGFILE ; then 
    echo "update: error: cvs -n update failed"
    exit 1
  fi
else 
  if ! cvs update $OPTIONS > $LOGFILE ; then
    echo "update: error: cvs update failed"
    exit 1
  fi
fi

CHANGES=
EXTCNT=0
for EXTENSION in $EXTENSIONS ; do
  (( ++EXTCNT ))
  cat $LOGFILE | grep -q "\."$EXTENSION 
  if (( $? != 0 )) ; then continue ; fi
  CHANGES="TRUE"
  DESCCNT=0
  for DESCRIPTION in $DESCRIPTIONS ; do
    (( ++DESCCNT ))
    if (( $DESCCNT == $EXTCNT )) ; then break ; fi
  done
  COLCNT=0
  for COLOUR in $COLOURS ; do
    (( ++COLCNT ))
    if (( $COLCNT == $EXTCNT )) ; then break ; fi
  done
  echo -en "\e[1m==================================================\e[0m"
  echo -e "\r\e[1m=\e[3"$COLOUR"m $DESCRIPTION \e[0m"
  cat $LOGFILE | grep "U " | grep "\."$EXTENSION
  cat $LOGFILE | grep "P " | grep "\."$EXTENSION
  cat $LOGFILE | grep "C " | grep "\."$EXTENSION > $TEMPFILE
  if (( $? == 0 )) ; then
    echo -e "\e[1m- Conflicts --------------------------------------\e[0m" 
    cat $TEMPFILE
  fi
  cat $LOGFILE | grep "M " | grep "\."$EXTENSION > $TEMPFILE
  if (( $? == 0 )) ; then
    echo -e "\e[1m- Changes ----------------------------------------\e[0m" 
    cat $TEMPFILE
  fi
  cat $LOGFILE | grep "erging " | grep "\."$EXTENSION > $TEMPFILE
  if (( $? == 0 )) ; then
    echo -e "\e[1m- Merged -----------------------------------------\e[0m" 
    cat $TEMPFILE
  fi
  cat $LOGFILE | grep "? " | grep "\."$EXTENSION > $TEMPFILE
  TEST1=$?
  cat $LOGFILE | grep "A " | grep "\."$EXTENSION >> $TEMPFILE
  TEST2=$?
  if (( $TEST1 == 0 )) || (( $TEST2 == 0 )) ; then
    echo -e "\e[1m- New files --------------------------------------\e[0m" 
    cat $TEMPFILE
  fi
  cat $LOGFILE | grep "R " | grep "\."$EXTENSION > $TEMPFILE
  if (( $? == 0 )) ; then
    echo -e "\e[1m- Removed files ----------------------------------\e[0m" 
    cat $TEMPFILE
  fi
done
echo -e "\e[1m==================================================\e[0m"
if [ ! "$CHANGES" = "TRUE" ] ; then
  echo -e "update: no recognized changes"
  echo -e "\e[1m==================================================\e[0m"
fi

if test -f $TEMPFILE ; then rm $TEMPFILE ; fi
if [ ! "$CLOGFILE" = "TRUE" ] ; then
  rm $LOGFILE
fi

# mode:shell-script
# sh-indentation:2
